
<form action="<?php echo $this->serverUrl($this->url()); ?>" method="get" name="search" id="search-form">
    <dl class="form">
        <dt class="date-start"><?php echo $this->search_form->start_date->getLabel(); ?></dt>
        <dd class="date-start">
            <?php echo $this->search_form->start_date->renderViewHelper(); ?>
            <?php echo $this->search_form->start_date->renderErrors(); ?>
        </dd>
        <dt class="date-end"><?php echo $this->search_form->end_date->getLabel(); ?></dt>
        <dd class="date-end">
            <?php echo $this->search_form->end_date->renderViewHelper(); ?>
            <?php echo $this->search_form->end_date->renderErrors(); ?>
        </dd>
        <dt class="search"><?php echo $this->search_form->search->getLabel(); ?></dt>
        <dd class="search">
            <?php echo $this->search_form->search->renderViewHelper(); ?>
            <?php echo $this->search_form->search->renderErrors(); ?>
        </dd>
    </dl>
    <p class="submit">
        <input type="submit" value="Search">
        <?php echo $this->search_form->sort->renderViewHelper(); ?>
        <?php echo $this->search_form->sort_dir->renderViewHelper(); ?>
    </p>
</form>

<?php
if ($this->payments) {

    $pagination = $this->paginationControl($this->paginator, 'Sliding', 'pagination/default.phtml', array('params' => $this->params));
    echo $pagination;
    echo $this->objectsToAdminTable(array(
        'order_id'     => array('title'  => 'Order ID'),
        'date'   => array('title' => 'Date', 'format' => 'datetime'),
        'email' => array(
            'title'    => 'Email',
            'callback' => function($row) { return $row->order->email; }
        ),
        'billing_first_name' => array(
            'title'    => 'First Name',
            'callback' => function($row) { return $row->order->billing_first_name; }
        ),
        'billing_last_name' => array(
            'title'    => 'Last Name',
            'callback' => function($row) { return $row->order->billing_last_name; }
        ),
        'amount'              => array(
            'title'   => 'Total',
            'format'  => 'dollar'
        ),
        'view'               => array(
            'format'  => 'link',
            'label'   => 'View',
            'url'     => '/admin/payments/detail/id'
        )
    ), $this->payments, $this->params, array('sortable' => true));
    echo $pagination;
} else {
    echo '<p class="error">There are no payments to show</p>';
}
?>

