
<div id="payments">
    <?php echo $this->render('forms/search.phtml'); ?>

    <?php
    if ($this->payments) {

        $pagination = $this->paginationControl($this->paginator, 'Sliding', 'pagination/default.phtml', array('params' => $this->params));
        echo $pagination;
        echo $this->objectsToAdminTable(array(
            'order_id'     => array('title'  => 'Order ID'),
            'date'   => array('title' => 'Date', 'format' => 'datetime'),
            'email' => array(
                'title'    => 'Email',
                'callback' => function($row) { return $row->order->email; }
            ),
            'billing_first_name' => array(
                'title'    => 'First Name',
                'callback' => function($row) { return $row->order->billing_first_name; }
            ),
            'billing_last_name' => array(
                'title'    => 'Last Name',
                'callback' => function($row) { return $row->order->billing_last_name; }
            ),
            'amount'              => array(
                'title'   => 'Total',
                'format'  => 'dollar'
            ),
            'view'               => array(
                'format'  => 'link',
                'label'   => 'View',
                'url'     => '/admin/payments/detail/id'
            )
        ), $this->payments, $this->params, array('sortable' => true));
        echo $pagination;
    } else {
        echo '<p class="error">There are no payments to show</p>';
    }
    ?>
</div>
