
<div id="cart">
    <form action="<?php echo $this->serverUrl($this->url()); ?>" method="post" name="cart">
        <fieldset class="account">
            <legend>Shopping Cart</legend>
            <?php if (count($this->cart->products)): ?>
                <?php echo $this->flashMessenger($this->messages); ?>
                <div class="items form">
                    <ul> 
                        <?php $c = 1; foreach ($this->cart->products as $product): ?>
                        <li class="item<?php echo ($c == count($this->cart->products) ? ' last' : ''); ?>">
                            <div class="cart-left">
                                <h4><?php echo $this->escape($product->getFullName()); ?></h4>
                                <?php
                                switch ($product->product_type_id) {
                                    case Model_ProductType::SUBSCRIPTION:
                                        $details = $this->escape("{$product->zone} - {$product->term} years - ") .
                                             $this->dollarFormat($product->cost);
                                        break;
                                    default:
                                        $details = $this->dollarFormat($product->cost);
                                        break;
                                }
                                ?>
                                <div class="details"><?php echo $details; ?></div>
                                <?php
                                // Qty input
                                $qty = $this->cart_form->qty->getElement($product->key);
                                if ($qty) {
                                    echo $qty->renderLabel() . $qty->renderViewHelper();
                                }
                                ?>
                                <ul class="links">
                                    <?php if ($this->nolayout && !$qty->getAttrib('readonly')): ?>
                                    <li>
                                        <a href="<?php echo $this->serverUrl($this->url(array())); ?>" class="update">Update</a>
                                    </li>
                                    <?php endif; ?>
                                    <li>
                                        <a href="<?php echo $this->serverUrl($this->url(array('key' => $product->key),
                                                               'cart_remove')); ?>" class="remove">Remove</a>
                                    </li>
                                </ul>
                                <?php
                                if ($qty) {
                                    echo $qty->renderErrors();
                                }
                                ?>
                            </div>
                            <div class="cart-right">
                                <?php echo $this->productThumbnail($product); ?>
                            </div>
                        </li>
                        <?php $c++; endforeach; ?>
                    </ul>
                </div>
                <p class="total-qty">You have <?php echo count($this->cart->products); ?> item<?php echo (count($this->cart->products) > 1 ? 's' : ''); ?> in your cart</p>
            <?php else: ?>
                <p class="no-items">You have no items in your cart</p> 
            <?php endif; ?>
            <ul class="cart-nav submit">
                <?php if ($this->nolayout): ?>
                    <li class="continue-shopping">
                        <input type="submit" value="Continue Shopping" class="button-grad">
                    </li>
                    <?php if (count($this->cart->products)): ?>
                    <li class="checkout">
                        <input type="submit" value="Checkout" class="button-grad">
                    </li>
                    <?php endif; ?>
                <?php else: ?>
                    <li class="submit"><input type="submit" value="Update" class="button-grad"></li>
                <?php endif; ?>
            </ul>
        </fieldset>
    </form>

</div>
