
<div id="cart">
    <form action="<?php echo $this->serverUrl($this->url()); ?>" method="post" name="cart">
        <fieldset class="account">
            <legend>Shopping Cart</legend>
            <?php if (count($this->cart->products)): ?>
                <?php echo $this->flashMessenger($this->messages); ?>
                <div class="items form">
                    <p>You will get:</p>
                    <ul> 
                        <?php $c = 1; foreach ($this->cart->products as $product): ?>
                        <li class="item<?php echo ($c == count($this->cart->products) ? ' last' : ''); ?>">
                            <p class="description"><?php echo $this->escape($this->truncate($product->description, 0, 200)); ?></p>
                            <?php 
                            /* See if there's a promo, and if it "belongs" to this product. Also, show only once. */
                            if (!isset($promo_shown) && $this->cart->promo && is_array($this->cart->promo->promo_products)  &&
                                in_array($product->id, array_keys($this->cart->promo->promo_products))): ?>
                                <p class="promo"><?php echo $this->escape($this->truncate($this->cart->promo->description, 0, 200)); ?></p>
                            <?php $promo_shown = true; endif; ?>
                            <?php
                            // Qty input
                            $qty = $this->cart_form->qty->getElement($product->key);
                            if ($qty) {
                                echo $qty->renderLabel() . $qty->renderViewHelper();
                            }
                            ?>
                            <ul class="links">
                                <?php if ($this->nolayout && !$qty->getAttrib('readonly')): ?>
                                <li>
                                    <a href="<?php echo $this->serverUrl($this->url(array())); ?>" class="update">Update</a>
                                </li>
                                <?php endif; ?>
                                <li>
                                    <a href="<?php echo $this->serverUrl($this->url(array('key' => $product->key), 'cart_remove')); ?>" class="remove">Remove</a>
                                </li>
                            </ul>
                            <?php
                            if ($qty) {
                                echo $qty->renderErrors();
                            }
                            ?>
                        </li>
                        <?php $c++; endforeach; ?>
                    </ul>
                </div>
                <p class="total-qty">You have <?php echo count($this->cart->products); ?> item<?php echo (count($this->cart->products) > 1 ? 's' : ''); ?> in your cart</p>
            <?php else: ?>
                <p class="no-items">You have no items in your cart</p> 
            <?php endif; ?>
            <ul class="buttons-list">
                <?php if (count($this->cart->products)): ?>
                    <li class="update"><input type="submit" value="Update" class="button-grad"></li>
                    <li class="checkout">
                        <a href="<?php echo $this->serverUrl($this->url(array(), 'checkout')); ?>" class="button-grad-yellow">Checkout</a>
                    </li>
                <?php endif; ?>
                <li class="continue-shopping">
                    <a href="<?php echo $this->serverUrl($this->url(array(), 'products')); ?>" class="">Continue Shopping</a>
                </li>
            </ul>
        </fieldset>
    </form>

</div>
