
<?php if ($this->password_updated): ?><p class="flash-message">Password updated</p><?php endif; ?>
<form action="<?php echo $this->serverUrl($this->url()); ?>" method="<?php echo $this->pw_form->getMethod(); ?>" name="<?php echo $this->pw_form->getName(); ?>">
    <fieldset class="account">
        <legend>Change Password</legend>
        <dl class="form">
            <dt><?php echo $this->pw_form->password->getLabel(); ?></dt>
            <dd>
                <?php echo $this->pw_form->password->renderViewHelper(); ?>
                <?php echo $this->pw_form->password->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->pw_form->new_password->getLabel(); ?></dt>
            <dd>
                <?php echo $this->pw_form->new_password->renderViewHelper(); ?>
                <?php echo $this->pw_form->new_password->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->pw_form->confirm_new_password->getLabel(); ?></dt>
            <dd>
                <?php echo $this->pw_form->confirm_new_password->renderViewHelper(); ?>
                <?php echo $this->pw_form->confirm_new_password->renderErrors(); ?>
            </dd>
        </dl>
    </fieldset>
    <p class="update"><input type="submit" value="Update" id="update-submit"></p>
</form>

