
<?php if ($this->profile_updated): ?><p class="flash-message">Profile updated</p><?php endif; ?>
<form action="<?php echo $this->serverUrl($this->url()); ?>" method="<?php echo $this->profile_form->getMethod(); ?>" name="<?php echo $this->profile_form->getName(); ?>">
    <fieldset>
        <legend>Account Information</legend>
        <dl class="form">
            <dt><?php echo $this->profile_form->username->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->username->renderViewHelper(); ?>
                <?php echo $this->profile_form->username->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->email->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->email->renderViewHelper(); ?>
                <?php echo $this->profile_form->email->renderErrors(); ?>
            </dd>
            <dt>Expiration</dt>
            <dd><?php echo $this->escape($this->subscription->expiration); ?></dd>
        </dl>
    </fieldset>
    <fieldset>
        <legend>Billing Information</legend>
        <dl class="form">
            <dt><?php echo $this->profile_form->first_name->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->first_name->renderViewHelper(); ?>
                <?php echo $this->profile_form->first_name->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->last_name->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->last_name->renderViewHelper(); ?>
                <?php echo $this->profile_form->last_name->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->billing_address->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->billing_address->renderViewHelper(); ?>
                <?php echo $this->profile_form->billing_address->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->billing_address_2->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->billing_address_2->renderViewHelper(); ?>
                <?php echo $this->profile_form->billing_address_2->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->billing_company->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->billing_company->renderViewHelper(); ?>
                <?php echo $this->profile_form->billing_company->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->billing_city->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->billing_city->renderViewHelper(); ?>
                <?php echo $this->profile_form->billing_city->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->billing_state->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->billing_state->renderViewHelper(); ?>
                <?php echo $this->profile_form->billing_state->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->billing_postal_code->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->billing_postal_code->renderViewHelper(); ?>
                <?php echo $this->profile_form->billing_postal_code->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->billing_country->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->billing_country->renderViewHelper(); ?>
                <?php echo $this->profile_form->billing_country->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->billing_phone->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->billing_phone->renderViewHelper(); ?>
                <?php echo $this->profile_form->billing_phone->renderErrors(); ?>
            </dd>
        </dl>
    </fieldset>
    <fieldset>
        <legend>Shipping Information</legend>
        <dl class="form">
            <dt><?php echo $this->profile_form->shipping_first_name->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->shipping_first_name->renderViewHelper(); ?>
                <?php echo $this->profile_form->shipping_first_name->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->shipping_last_name->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->shipping_last_name->renderViewHelper(); ?>
                <?php echo $this->profile_form->shipping_last_name->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->shipping_address->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->shipping_address->renderViewHelper(); ?>
                <?php echo $this->profile_form->shipping_address->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->shipping_address_2->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->shipping_address_2->renderViewHelper(); ?>
                <?php echo $this->profile_form->shipping_address_2->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->shipping_company->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->shipping_company->renderViewHelper(); ?>
                <?php echo $this->profile_form->shipping_company->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->shipping_city->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->shipping_city->renderViewHelper(); ?>
                <?php echo $this->profile_form->shipping_city->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->shipping_state->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->shipping_state->renderViewHelper(); ?>
                <?php echo $this->profile_form->shipping_state->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->shipping_postal_code->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->shipping_postal_code->renderViewHelper(); ?>
                <?php echo $this->profile_form->shipping_postal_code->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->shipping_country->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->shipping_country->renderViewHelper(); ?>
                <?php echo $this->profile_form->shipping_country->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->shipping_phone->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->shipping_phone->renderViewHelper(); ?>
                <?php echo $this->profile_form->shipping_phone->renderErrors(); ?>
            </dd>
        </dl>
    </fieldset>
    <p class="update"><input type="submit" value="Update" id="update-submit"></p>
</form>

