
You're receiving this e-mail because you requested a password reset for your user account at <?php echo $this->serverUrl(); ?> 

Please go to the following page and choose a new password:

<?php echo $this->serverUrl($this->url(array('token' => $this->token), 'reset_password')); ?> 

Your username, in case you've forgotten: <?php echo $this->escape($this->user->username); ?> 

Thanks for using our site!

The PhotoshopElementsUser.com team


