
<form name="delete-shipping-zone" id="delete-shipping-zone" method="post" action="">
    <?php if ($this->status): ?>
        <h2>Shipping zone deleted</h2>
    <?php else: ?>
        <h2>Error</h2>
        <p class="error">An error has occurred. Maybe this shipping zone is already in use by other tables?</p>
    <?php endif; ?>
    <input type="submit" value="Close" id="close">
    <input type="hidden" value="<?php echo (int) $this->status; ?>" name="status">
</form>
