
<form name="delete-shipping-zone-dialog" id="delete-shipping-zone-dialog" method="post" action="">
    <h2><strong>Are you sure you want to delete shipping zone #<?php echo $this->escape($this->shipping_zone->id); ?>?</strong></h2>
    <p>
        <input type="hidden" name="id" value="<?php echo $this->escape($this->shipping_zone->id); ?>">
        <input type="submit" id="submit" value="Submit">
        <input type="submit" id="cancel" value="Cancel">
    </p>
</form>
