<div id="promo-edit">
    <?php echo $this->flashMessenger($this->messages); ?>
    <form action="" method="<?php echo $this->promo_form->getMethod(); ?>" name="<?php echo $this->promo_form->getName(); ?>" enctype="<?php echo $this->promo_form->getEnctype(); ?>">
        <fieldset class="promo">
            <dl class="form">
                <dt><?php echo $this->promo_form->code->renderLabel(); ?></dt>
                <dd>
                    <?php echo $this->promo_form->code->renderViewHelper(); ?>
                    <?php echo $this->promo_form->code->renderErrors(); ?>
                </dd>
                <dt><?php echo $this->promo_form->expiration->renderLabel(); ?></dt>
                <dd>
                    <?php echo $this->promo_form->expiration->renderViewHelper(); ?>
                    <?php echo $this->promo_form->expiration->renderErrors(); ?>
                </dd>
                <dt><?php echo $this->promo_form->description->renderLabel(); ?></dt>
                <dd class="textarea">
                    <?php echo $this->promo_form->description->renderViewHelper(); ?>
                    <?php echo $this->promo_form->description->renderErrors(); ?>
                </dd>
                <dt><?php echo $this->promo_form->public_description->renderLabel(); ?></dt>
                <dd class="textarea">
                    <?php echo $this->promo_form->public_description->renderViewHelper(); ?>
                    <?php echo $this->promo_form->public_description->renderErrors(); ?>
                </dd>
                <dt><?php echo $this->promo_form->receipt_description->renderLabel(); ?></dt>
                <dd class="textarea">
                    <?php echo $this->promo_form->receipt_description->renderViewHelper(); ?>
                    <?php echo $this->promo_form->receipt_description->renderErrors(); ?>
                </dd>
                <dt><?php echo $this->promo_form->banner->renderLabel(); ?></dt>
                <dd class="image">
                    <?php echo $this->promo_form->banner->renderFile(); ?>
                    <?php echo $this->promo_form->banner->renderErrors(); ?>
                    <?php if ($this->banner): ?>
                        <div id="banner-image">
                            <p><img src="<?php echo $this->escape($this->banner); ?>"></p>
                            <a href="#" class="delete-banner">Remove</a>
                        </div>
                    <?php endif; ?>
                </dd>
                <dt><?php echo $this->promo_form->discount->renderLabel(); ?></dt>
                <dd>
                    <?php echo $this->promo_form->discount->renderViewHelper(); ?>
                    <?php echo $this->promo_form->discount->renderErrors(); ?>
                </dd>
                <dt><?php echo $this->promo_form->extra_days->renderLabel(); ?></dt>
                <dd>
                    <?php echo $this->promo_form->extra_days->renderViewHelper(); ?>
                    <?php echo $this->promo_form->extra_days->renderErrors(); ?>
                </dd>
                <dt><?php echo $this->promo_form->products->renderLabel(); ?></dt>
                <dd>
                    <?php echo $this->promo_form->products->renderViewHelper(); ?>
                    <?php echo $this->promo_form->products->renderErrors(); ?>
                </dd>
            </dl>
        </fieldset>
        <p class="update clear">
            <?php echo $this->promo_form->tmp_banner->renderViewHelper(); ?>
            <?php echo $this->promo_form->delete_banner->renderViewHelper(); ?>
            <input type="submit" value="Submit" class="submit">
            <input type="submit" value="Cancel" name="cancel">
        </p>
    </form>
</div>
