
<div id="promos">
    <form action="<?php echo $this->serverUrl($this->url()); ?>" method="get" name="search" id="search-form">
        <dl class="form">
            <dt class="code"><?php echo $this->search_form->code->renderLabel(); ?></dt>
            <dd class="code">
                <?php echo $this->search_form->code->renderViewHelper(); ?>
                <?php echo $this->search_form->code->renderErrors(); ?>
            </dd>
            <dt class="date-start"><?php echo $this->search_form->date_range->start_date->renderLabel(); ?></dt>
            <dd class="date-start">
                <?php echo $this->search_form->date_range->start_date->renderViewHelper(); ?>
                <?php echo $this->search_form->date_range->start_date->renderErrors(); ?>
            </dd>
            <dt class="date-end"><?php echo $this->search_form->date_range->end_date->renderLabel(); ?></dt>
            <dd class="date-end">
                <?php echo $this->search_form->date_range->end_date->renderViewHelper(); ?>
                <?php echo $this->search_form->date_range->end_date->renderErrors(); ?>
            </dd>
        </dl>
        <p class="submit">
            <input type="submit" value="Search">
            <?php echo $this->search_form->sort->renderViewHelper(); ?>
            <?php echo $this->search_form->sort_dir->renderViewHelper(); ?>
        </p>
    </form>
    <?php
    if ($this->promos) {
        $pagination = $this->paginationControl($this->paginator, 'Sliding', 'pagination/default.phtml', array('params' => $this->params));
        echo $pagination;
        $view = $this;
        echo $this->objectsToAdminTable(array(
            'id' => array('title'  => 'ID'),
            'code',
            'expiration' => array(
                'format' => 'date'
            ),
            'discount' => array(
                'format' => 'dollar'
            ),
            'edit' => array(
                'format'  => 'link',
                'label'   => 'Edit',
                'url'     => '/admin/promos/edit/id'
            ),
            'delete' => array(
                'title'    => '',
                'callback' => function($data) use ($view) {
                    return '<a href="' . $view->serverUrl($view->url(array('action' => 'delete-dialog', 'id' => $data->id))) . '" class="delete">Delete</a>';
                }
            )
        ), $this->promos, $this->params, array('sortable' => true));
        echo $pagination;
    } else {
        echo '<p class="error">There are no promos to show</p>';
    }
    ?>
</div>

