

<fieldset class="download clear">
    <dl class="form">
        <dt><?php echo $this->product_form->download->download_format_id->renderLabel(); ?></dt>
        <dd>
            <?php echo $this->product_form->download->download_format_id->renderViewHelper(); ?>
            <?php echo $this->product_form->download->download_format_id->renderErrors(); ?>
        </dd>
        <dt><?php echo $this->product_form->download->date->renderLabel(); ?></dt>
        <dd>
            <?php echo $this->product_form->download->date->renderViewHelper(); ?>
            <?php echo $this->product_form->download->date->renderErrors(); ?>
        </dd>
        <dt><?php echo $this->product_form->download->path->renderLabel(); ?></dt>
        <dd>
            <?php echo $this->product_form->download->path->renderViewHelper(); ?>
            <?php echo $this->product_form->download->path->renderErrors(); ?>
        </dd>
        <dt><?php echo $this->product_form->download->size->renderLabel(); ?></dt>
        <dd>
            <?php echo $this->product_form->download->size->renderViewHelper(); ?>
            <?php echo $this->product_form->download->size->renderErrors(); ?>
        </dd>
        <dt><?php echo $this->product_form->download->subscriber_only->renderLabel(); ?></dt>
        <dd>
            <?php echo $this->product_form->download->subscriber_only->renderViewHelper(); ?>
            <?php echo $this->product_form->download->subscriber_only->renderErrors(); ?>
        </dd>
    </dl>
</fieldset>
