

<div id="product-edit">
    <?php echo $this->flashMessenger($this->messages); ?>
    <form action="<?php echo $this->product_form->getAction(); ?>" method="<?php echo $this->product_form->getMethod(); ?>" name="<?php echo $this->product_form->getName(); ?>">
        <fieldset class="products">
            <legend>Product</legend>
            <dl class="form">
                <dt><?php echo $this->product_form->name->renderLabel(); ?></dt>
                <dd>
                    <?php echo $this->product_form->name->renderViewHelper(); ?>
                    <?php echo $this->product_form->name->renderErrors(); ?>
                </dd>
                <dt><?php echo $this->product_form->product_type->renderLabel(); ?></dt>
                <dd>
                    <?php echo $this->product_form->product_type->renderViewHelper(); ?>
                    <?php echo $this->product_form->product_type->renderErrors(); ?>
                </dd>
                <dt><?php echo $this->product_form->sku->renderLabel(); ?></dt>
                <dd>
                    <?php echo $this->product_form->sku->renderViewHelper(); ?>
                    <?php echo $this->product_form->sku->renderErrors(); ?>
                </dd>
                <dt><?php echo $this->product_form->cost->renderLabel(); ?></dt>
                <dd>
                    <?php echo $this->product_form->cost->renderViewHelper(); ?>
                    <?php echo $this->product_form->cost->renderErrors(); ?>
                </dd>
                <dt><?php echo $this->product_form->active->renderLabel(); ?></dt>
                <dd>
                    <?php echo $this->product_form->active->renderViewHelper(); ?>
                    <?php echo $this->product_form->active->renderErrors(); ?>
                </dd>
                <dt><?php echo $this->product_form->is_giftable->renderLabel(); ?></dt>
                <dd>
                    <?php echo $this->product_form->is_giftable->renderViewHelper(); ?>
                    <?php echo $this->product_form->is_giftable->renderErrors(); ?>
                </dd>
            </dl>
        </fieldset>
        <?php
        switch ($this->product->product_type_id) {
            case Model_ProductType::SUBSCRIPTION:
                echo $this->render('products/subscription-form.phtml');
                break;
            case Model_ProductType::DOWNLOAD:
                echo $this->render('products/download-form.phtml');
                break;
            case Model_ProductType::PHYSICAL:
                echo $this->render('products/physical-form.phtml');
                break;
            case Model_ProductType::COURSE:
                echo $this->render('products/course-form.phtml');
                break;
            case Model_ProductType::DIGITAL_SUBSCRIPTION:
                echo $this->render('products/digital-form.phtml');
                break;
        }
        ?>
        <p class="update clear">
            <input type="submit" value="Submit" class="submit">
            <input type="submit" value="Cancel" name="cancel">
        </p>
    </form>
</div>
<pre>
<?php print_r($this->product); ?>
</pre>
