
<div id="product-edit">
    <?php echo $this->flashMessenger($this->messages); ?>
    <form action="<?php echo $this->product_form->getAction(); ?>" method="<?php echo $this->product_form->getMethod(); ?>" name="<?php echo $this->product_form->getName(); ?>">
        <fieldset class="products">
            <legend>Product</legend>
            <dl class="form">
                <dt><?php echo $this->product_form->name->renderLabel(); ?></dt>
                <dd>
                    <?php echo $this->product_form->name->renderViewHelper(); ?>
                    <?php echo $this->product_form->name->renderErrors(); ?>
                </dd>
                <dt><?php echo $this->product_form->product_type_id->renderLabel(); ?></dt>
                <dd>
                    <?php echo $this->product_form->product_type_id->renderViewHelper(); ?>
                    <?php echo $this->product_form->product_type_id->renderErrors(); ?>
                </dd>
                <dt><?php echo $this->product_form->sku->renderLabel(); ?></dt>
                <dd>
                    <?php echo $this->product_form->sku->renderViewHelper(); ?>
                    <?php echo $this->product_form->sku->renderErrors(); ?>
                </dd>
                <dt><?php echo $this->product_form->description->renderLabel(); ?></dt>
                <dd>
                    <?php echo $this->product_form->description->renderViewHelper(); ?>
                    <?php echo $this->product_form->description->renderErrors(); ?>
                </dd>
                <dt><?php echo $this->product_form->short_description->renderLabel(); ?></dt>
                <dd>
                    <?php echo $this->product_form->short_description->renderViewHelper(); ?>
                    <?php echo $this->product_form->short_description->renderErrors(); ?>
                </dd>
                <dt><?php echo $this->product_form->cost->renderLabel(); ?></dt>
                <dd>
                    <?php echo $this->product_form->cost->renderViewHelper(); ?>
                    <?php echo $this->product_form->cost->renderErrors(); ?>
                </dd>
                <dt><?php echo $this->product_form->active->renderLabel(); ?></dt>
                <dd>
                    <?php echo $this->product_form->active->renderViewHelper(); ?>
                    <?php echo $this->product_form->active->renderErrors(); ?>
                </dd>
                <dt><?php echo $this->product_form->is_giftable->renderLabel(); ?></dt>
                <dd>
                    <?php echo $this->product_form->is_giftable->renderViewHelper(); ?>
                    <?php echo $this->product_form->is_giftable->renderErrors(); ?>
                </dd>
            </dl>
        </fieldset>
        <div id="product-subform">
            <?php
            switch ($this->product_type_id) {
                case Model_ProductType::SUBSCRIPTION:
                    echo $this->render('products/subscription-form.phtml');
                    break;
                case Model_ProductType::DOWNLOAD:
                    echo $this->render('products/download-form.phtml');
                    break;
                case Model_ProductType::PHYSICAL:
                    echo $this->render('products/physical-form.phtml');
                    break;
                case Model_ProductType::COURSE:
                    echo $this->render('products/course-form.phtml');
                    break;
                case Model_ProductType::DIGITAL_SUBSCRIPTION:
                    echo $this->render('products/digital-form.phtml');
                    break;
            }
            ?>
        </div>
        <p class="update clear">
            <?php
            /* In case product_type_id is disabled */
            if ($this->product_form->product_type_id_2) {
                echo $this->product_form->product_type_id_2->renderViewHelper();
            }
            ?>
            <input type="submit" value="Submit" class="submit">
            <input type="submit" value="Cancel" name="cancel">
        </p>
    </form>
</div>
