
<div id="products">
    <form action="<?php echo $this->filter_form->getAction(); ?>" method="<?php echo $this->filter_form->getMethod(); ?>" name="<?php echo $this->filter_form->getName(); ?>" id="search-form">
        <dl class="form">
            <dt><?php echo $this->filter_form->product_type->renderLabel(); ?></dt>
            <dd>
                <?php echo $this->filter_form->product_type->renderViewHelper(); ?>
                <?php echo $this->filter_form->product_type->renderErrors(); ?>
            </dd>
        </dl>
        <p class="submit">
            <input type="submit" value="Search">
        </p>
    </form>
    <?php
    if ($this->products) {
        $view = $this;
        $pagination = $this->paginationControl($this->paginator, 'Sliding', 'pagination/default.phtml', array('params' => $this->params));
        echo $pagination;
        echo $this->objectsToAdminTable(array(
            'id' => array('title'  => 'Product ID'),
            'sku' => array('title' => 'SKU'),
            'name',
            'product_type_id' => array(
                'title' => 'Product Type',
                'callback' => function($data) {
                    switch ($data->product_type_id) {
                        case Model_ProductType::SUBSCRIPTION:
                            return 'Subscription';
                        case Model_ProductType::DIGITAL_SUBSCRIPTION:
                            return 'Digital Subscription';
                        case Model_ProductType::PHYSICAL:
                            return 'Physical Product';
                        case Model_ProductType::COURSE:
                            return 'Course';
                        case Model_ProductType::DOWNLOAD:
                            return 'Download';
                    }
                }
            ),
            'cost' => array(
                'format' => 'dollar'
            ),
            'active' => array(
                'callback' => function($data) {
                    return ($data->active ? 'Y' : 'N');
                }
            ),
            'edit' => array(
                'format'  => 'link',
                'label'   => 'Edit',
                'url'     => '/admin/products/edit/id'
            ),
            'delete' => array(
                'title'    => '',
                'callback' => function($data) use ($view) {
                    return '<a href="' . $view->serverUrl($view->url(array('action' => 'delete-dialog', 'id' => $data->product_id))) . '" class="delete">Delete</a>';
                }
            )
        ), $this->products);
        echo $pagination;
    } else {
        echo '<p class="error">There are no products to show</p>';
    }
    ?>
</div>

