
<?php $this->product_form->subscription; ?>
<fieldset class="subscription clear">
    <dl class="form">
        <dt><?php echo $this->product_form->subscription->zone_id->renderLabel(); ?></dt>
        <dd>
            <?php echo $this->product_form->subscription->zone_id->renderViewHelper(); ?>
            <?php echo $this->product_form->subscription->zone_id->renderErrors(); ?>
        </dd>
        <dt><?php echo $this->product_form->subscription->term_months->renderLabel(); ?></dt>
        <dd>
            <?php echo $this->product_form->subscription->term_months->renderViewHelper(); ?>
            <?php echo $this->product_form->subscription->term_months->renderErrors(); ?>
        </dd>
        <dt><?php echo $this->product_form->subscription->is_renewal->renderLabel(); ?></dt>
        <dd>
            <?php echo $this->product_form->subscription->is_renewal->renderViewHelper(); ?>
            <?php echo $this->product_form->subscription->is_renewal->renderErrors(); ?>
        </dd>
    </dl>
</fieldset>
