
<fieldset class="subscription clear">
    <dl class="form">
        <dt><?php echo $this->product_form->subscription->download_format->renderLabel(); ?></dt>
        <dd>
            <?php echo $this->product_form->subscription->download_format->renderViewHelper(); ?>
            <?php echo $this->product_form->subscription->download_format->renderErrors(); ?>
        </dd>
    </dl>
</fieldset>
