
<form action="<?php echo $this->serverUrl($this->url()); ?>" method="get" name="search" id="search-form">
    <dl class="form">
        <dt class="date-start datepicker"><?php echo $this->search_form->date_range->start_date->renderLabel(); ?></dt>
        <dd class="date-start datepicker">
            <?php echo $this->search_form->date_range->start_date->renderViewHelper(); ?>
            <?php echo $this->search_form->date_range->start_date->renderErrors(); ?>
        </dd>
        <dt class="date-end datepicker"><?php echo $this->search_form->date_range->end_date->renderLabel(); ?></dt>
        <dd class="date-end datepicker">
            <?php echo $this->search_form->date_range->end_date->renderViewHelper(); ?>
            <?php echo $this->search_form->date_range->end_date->renderErrors(); ?>
        </dd>
        <dt class="search"><?php echo $this->search_form->search->renderLabel(); ?></dt>
        <dd class="search">
            <?php echo $this->search_form->search->renderViewHelper(); ?>
            <?php echo $this->search_form->search->renderErrors(); ?>
        </dd>
    </dl>
    <p class="submit">
        <input type="submit" value="Search">
        <?php echo $this->search_form->sort->renderViewHelper(); ?>
        <?php echo $this->search_form->sort_dir->renderViewHelper(); ?>
    </p>
</form>
