
<?php /* Generic pagination view */ ?>

<?php
$this->params = (isset($this->params) ? $this->params : array());
unset($this->params['page']);
if ($this->pageCount):
?>
<ul class="pagination">
    <?php if (isset($this->previous)): ?>
        <li class="text-link">
            <a href="<?php echo $this->url() . '?' . $this->escape(http_build_query(array_merge(array('page' => $this->first), $this->params))); ?>">First</a> 
        </li>
    <?php else: ?>
        <li class="disabled text-link"><span>First</span></li>
    <?php endif; ?>
    <?php if (isset($this->previous)): ?>
        <?php /* Not passing the parameters into the url() view helper because it and the router don't play nice together */ ?>
        <li class="prev-next">
            <a href="<?php echo $this->url() . '?' . $this->escape(http_build_query(array_merge(array('page' => $this->previous), $this->params))); ?>">&lt; Previous</a>
        </li>
    <?php else: ?>
        <li class="disabled prev-next"><span>&lt; Previous</span></li>
    <?php endif; ?>
    <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
            <li>
                <a href="<?php echo $this->url() . '?' . $this->escape(http_build_query(array_merge(array('page' => $page), $this->params))); ?>"><?php echo $page; ?></a>
            </li>
        <?php else: ?>
            <li class="current"><span><?php echo $page; ?></span></li>
        <?php endif; ?>
    <?php endforeach; ?>
    <?php if (isset($this->next)): ?>
        <li class="prev-next">
            <a href="<?php echo $this->url() . '?' . $this->escape(http_build_query(array_merge(array('page' => $this->next), $this->params))); ?>">Next &gt;</a>
        </li>
    <?php else: ?>
        <li class="disabled prev-next"><span>Next &gt;</span></li>
    <?php endif; ?>
    <?php if (isset($this->next)): ?>
        <li class="text-link">
            <a href="<?php echo $this->url() . '?' . $this->escape(http_build_query(array_merge(array('page' => $this->last), $this->params))); ?>">Last</a> 
        </li>
    <?php else: ?>
        <li class="disabled text-link"><span>Last</span></li>
    <?php endif; ?>
</ul>
<?php endif; ?>
