<!DOCTYPE html> 
<html lang="en">
<head>
<title>Photoshop Elements Techniques, Tutorials, Downloads, Video Tips, Newsletter and more - Photoshop Elements User</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content="We offer how-to articles, tutorials and videos about Adobe Photoshop Elements. Get a free issue of Photoshop Elements magazine." />
<meta name="copyright" content="1999-<?php echo date('Y'); ?>, Photo One Media" />
<meta name="google-site-verification" content="yxFgFAShYWbqXMOs28hBBdBqeqiPh0LGs9e2-ocHe_E" />


<script type="text/javascript">
    document.domain = 'photoshopelementsuser.com';
</script>

<link rel="stylesheet" type="text/css" href="http://www.photoshopelementsuser.com/wp-content/themes/pet/style.css" />
<link rel="stylesheet" type="text/css" href="/css/base.css" />
<link rel="stylesheet" type="text/css" href="/css/fancybox/jquery.fancybox.css" />

<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>

</head>

<body id="iframe">
    
    <div id="content">
        <div class="container clearfix">
            <div id="main">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </div>
    <?php echo $this->headScriptMin()->loadGroup('common'); echo $this->inlineScriptMin(); ?>
</body>
</html>
