<!DOCTYPE html> 
<html lang="en">
<head>
<title>Photoshop Elements Techniques, Tutorials, Downloads, Video Tips, Newsletter and more - Photoshop Elements User</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content="We offer how-to articles, tutorials and videos about Adobe Photoshop Elements. Get a free issue of Photoshop Elements magazine." />
<meta name="copyright" content="1999-<?php echo date('Y'); ?>, Photo One Media" />
<meta name="google-site-verification" content="yxFgFAShYWbqXMOs28hBBdBqeqiPh0LGs9e2-ocHe_E" />


<?php
    
echo $this->headLink()
        ->prependStylesheet('/css/sections.css')
        ->prependStylesheet('/css/base.css')
        ->prependStylesheet('/css/fancybox/jquery.fancybox.css')
        ->prependStylesheet($this->fullUrl('/wp-content/themes/pet/style.css', 'www.photoshopelementsuser.com'));
?>

<!--[if IE 9]>
<style type="text/css">
#header #logo { width: 320px; }
</style>
<![endif]-->

<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
<link rel="alternate" type="application/rss+xml" href="<?php echo $this->fullUrl('/ElementsTechniques', 'feeds.feedburner.com'); ?>" />

<link rel="prev" title="Blog" href="<?php echo $this->fullUrl('/blog', 'www.photoshopelementsuser.com'); ?>" />
<link rel="next" title="Contest" href="<?php echo $this->fullUrl('/contest', 'www.photoshopelementsuser.com'); ?>" />

<link rel="shortlink" href="<?php echo $this->fullUrl('/PSCv8-5', 'wp.me'); ?>" />

<!--[if lt IE 9]>
<script src="/js/lib/html5.js"></script>
<![endif]-->

</head>

<body id="home">
    <div id="header">
        <div class="container">
            <div id="logo">
                <a href="/"><img src="<?php echo $this->fullUrl('/wp-content/themes/pet/_img/pet-logo.png', 'www.photoshopelementsuser.com'); ?>" alt="Photoshop Elements Techniques" /></a>
            </div>
            <div id="nav-wrap">
                <ul id="top-nav" class="clearfix">
                    <li><a href="/topics/" class="top-level-link">Topics</a>
                        <div>
                            <p><a href="/tag/elements-10/"><span class="nav-title">Elements 10</span></a> <span class="nav-desc">- Articles covering Elements 10.</span></p>
                            <p><a href="/tag/elements-9/"><span class="nav-title">Elements 9</span></a> <span class="nav-desc">- Articles covering Elements 9.</span></p>
                            <p><a href="/category/getting-started-editor/"><span class="nav-title">Getting Started (Editor)</span></a> <span class="nav-desc">- Working with the Editor.</span></p>
                            <p><a href="/category/getting-started-organizer/"><span class="nav-title">Getting Started (Organizer)</span></a> <span class="nav-desc">- Working with the Organizer.</span></p>
                            <p><a href="/category/photo-editing/"><span class="nav-title">Photo Editing Techniques</span></a> <span class="nav-desc">- Enhance your photos and more.</span></p>
                            <p><a href="/category/photo-effects/"><span class="nav-title">Photo Effects</span></a> <span class="nav-desc">- Techniques to add effects to your photos.</span></p>
                            <p class="nav-all"><a href="/topics/">View all topics &raquo;</a></p>
                        </div>
                    </li>
                    <li><a href="/articles/" class="top-level-link">Tutorials</a>
                        <div>
                            <p><a href="/category/video/"><span class="nav-title">Videos</span></a> <span class="nav-desc">- Watch our online video tutorials.</span></p>
                            <p><a href="/category/pdf/"><span class="nav-title">PDFs</span></a> <span class="nav-desc">- Download PDF articles from the magazine.</span></p>
                            <p><a href="/category/html/"><span class="nav-title">Web tutorials</span></a> <span class="nav-desc">- View our Web-based articles and tutorials.</span></p>
                            <p><a href="/popular/"><span class="nav-title">Popular</span></a> <span class="nav-desc">- Our most popular tutorials.</span></p>
                            <p class="nav-all"><a href="/articles/">View all tutorials &raquo;</a></p>
                        </div>
                    </li>
                    <li>
                        <a href="/magazine/" class="top-level-link">Magazine</a>
                        <div>
                            <p><a href="/magazine/v9n2/"><span class="nav-title">March/April 2012 issue (online extras only)</span></a></p>
                            <p><a href="/magazine/v9n1/"><span class="nav-title">January/February 2012 issue</span></a></p>
                            <p><a href="/magazine/"><span class="nav-title">Previous Issues</span></a> <span class="nav-desc">- View all previously published magazine issues.</span></p>
                            <p><a href="/category/downloads/"><span class="nav-title">Extras/Downloads</span></a> <span class="nav-desc">- Magazine extras and other files to download.</span></p>
                            <p><a href="/from-the-editor/"><span class="nav-title">&#8220;From the Editor&#8221;</span></a><span class="nav-desc">- Email newsletters from P.E.T. editors</span></p>
                            <p class="nav-all"><a href="/magazine/">View all magazine issues &raquo;</a></p>
                        </div>
                    </li>
                    <li class="tl-store">
                        <a href="http://store.photoshopelementsuser.com/?utm_source=nav&amp;utm_medium=storeTab&amp;utm_campaign=topLink" class="top-level-link">Store</a>
                        <div>
                            <p><a href="/subscribe-6/?utm_source=nav&amp;utm_medium=storeTab&amp;utm_campaign=subscribe-6"><span class="nav-title">Subscribe</span></a> <span class="nav-desc">- Subscribe to our magazine.</span></p>
                            <p><a href="/renew/?utm_source=nav&amp;utm_medium=storeTab&amp;utm_campaign=renew"><span class="nav-title">Renew</span></a> <span class="nav-desc">- Renew your subscription.</span></p>
                            <p><a href="/products/dvd/learn_elements_today.html?utm_source=nav&amp;utm_medium=storeTab&amp;utm_campaign=LET"><span class="nav-title">Learn Elements Today!</span></a> <span class="nav-desc">- Buy our tutorial DVD.</span></p>
                            <p><a href="http://store.photoshopelementsuser.com/?utm_source=nav&amp;utm_medium=storeTab&amp;utm_campaign=DVDstore"><span class="nav-title">Other DVDs</span></a> <span class="nav-desc">- Our other tutorial DVDs.</span></p>
                            <p class="nav-all"><a href="http://store.photoshopelementsuser.com/?utm_source=nav&amp;utm_medium=storeTab&amp;utm_campaign=visitStore">Visit the store &raquo;</a></p>
                        </div>
                    </li>
                    <li class="tl-lc"><a href="/learningcenter/?utm_source=nav&amp;utm_medium=LearningCenterTab&amp;utm_campaign=learningCenter" class="top-level-link">Learning Center</a>
                        <div>
                            <p><a href="/elementsuser/?utm_source=nav&amp;utm_medium=LearningCenterTab&amp;utm_campaign=starterKit"><span class="nav-title">Starter Kit</span></a> - <span class="nav-desc">Get a free sample issue and more.</span></p>
                            <p><a href="/products/dvd/learn_elements_today.html?utm_source=nav&amp;utm_medium=LearningCenterTab&amp;utm_campaign=LET"><span class="nav-title">Learn Elements Today!</span></a> <span class="nav-desc">- Buy our tutorial DVD.</span></p>
                            <p class="nav-all"><a href="/learningcenter/?utm_source=nav&amp;utm_medium=LearningCenterTab&amp;utm_campaign=lastLink">Visit the Learning Center &raquo;</a></p>
                        </div>
                    </li>
                    <li class="last"><a href="/blog/?utm_source=nav&amp;utm_medium=CommunityTab&amp;utm_campaign=top" class="top-level-link">Community</a>
                        <div>
                            <p><a href="/blog/?utm_source=nav&amp;utm_medium=CommunityTab&amp;utm_campaign=blog"><span class="nav-title">The P.E.T. Blog</span></a> <span class="nav-desc">- Visit our blog.</span></p>
                            <p><a href="http://www.elementsvillage.com/?utm_source=nav&amp;utm_medium=CommunityTab&amp;utm_campaign=village"><span class="nav-title">Elements Village</span></a> <span class="nav-desc">- Visit our forums.</span></p>
                            <p><a href="/gallery/newest_images.php?utm_source=nav&amp;utm_medium=CommunityTab&amp;utm_campaign=gallery"><span class="nav-title">P.E.T. Gallery</span></a> <span class="nav-desc">- Visit our subscriber gallery.</span></p>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div id="top">
        <div class="container">
            <div class="col-wrap clearfix">
                <div class="col col-1">
                    <?php $this->getHelper('serverUrl')->setScheme('https'); ?>
                    <?php if ($user = Zend_Auth::getInstance()->getIdentity()): ?>
                        <p>Logged in as <?php echo $this->escape($user->username); ?>. <a href="<?php echo $this->serverUrl($this->url(array(), 'profile_edit')); ?>">Profile</a> &middot; <!--<a href="/favorites/">My Favorites</a> &middot;--> <a href="<?php echo $this->serverUrl($this->url(array(), 'profile_logout')); ?>">Log out</a> </p>
                    <?php else: ?>
                        <p>New user? <a href="/subscribe-6/?utm_source=nav&amp;utm_medium=SubscribeLink&amp;utm_campaign=subscribe-6">Subscribe</a>!&nbsp;&nbsp;&middot;&nbsp;&nbsp;Already a subscriber? <a href="<?php echo $this->serverUrl($this->url(array(), 'profile_login')); ?>"><span class="login">Log in</span></a>. </p>                    
                    <?php endif; ?>
                </div>
                <div class="col col-2">
                    <form method="get" id="search" action="/">
                        <div class="searchform">
                            <label for="s">Search the site:</label>
                            <input type="text" name="s" id="s" value="" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
    <div id="content">
        <div class="container clearfix">
            <div id="main">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </div>
    
    <div id="footer">
        <div class="container">
            <p>&copy; <?php echo date('Y'); ?> Copyright Photoshop Elements Techniques. All rights reserved.&nbsp;&nbsp;<a href="/help/">Help</a>&nbsp;&nbsp;&middot;&nbsp;&nbsp;<a href="/about/">About Us</a>&nbsp;&nbsp;&middot;&nbsp;&nbsp;<a href="/contact/">Contact Us</a>&nbsp;&nbsp;&middot;&nbsp;&nbsp;<a href="/privacy/">Privacy Policy</a>&nbsp;&nbsp;&middot;&nbsp;&nbsp;<a href="/terms/">Terms of Use</a></p>
            <p class="no-margin smaller">Adobe Photoshop Elements Techniques is published by Photo One Media.<br />Photo One is an independent company, and is not affiliated with Adobe Systems.<br />Adobe, Photoshop, and Premiere are registered trademarks of Adobe Systems Incorporated.</p>

        </div>
    </div>
    
    <?php echo $this->headScriptMin()->loadGroup('common'); echo $this->inlineScriptMin(); ?>

    <script type="text/javascript" src="<?php echo $this->fullUrl('/wp-content/themes/pet/_js/jquery.megamenu.js', 'www.photoshopelementsuser.com'); ?>"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $("#top-nav").megamenu();
        });
    </script>
    <!--<script type="text/javascript" src="http://www.photoshopelementsuser.com/wp-content/themes/pet/_js/cufon-yui.js"></script>
    <script type="text/javascript" src="http://www.photoshopelementsuser.com/wp-content/themes/pet/_js/graublau.font.js"></script>
    <script type="text/javascript" src="http://www.photoshopelementsuser.com/wp-content/themes/pet/_js/museo.font.js"></script>
    <script type="text/javascript">
        //Cufon.replace('#content h2, #bottom h2, #subscribe #content h1', { fontFamily: 'Graublau Web' });
        //Cufon.replace('#top #login h3, #content h3, p', { fontFamily: 'Museo', hover: true });
    </script>-->

    <!--<script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-3966700-2']);
        _gaq.push(['_trackPageview']);
        (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>-->
</body>
</html>
