
<form action="<?php echo $this->serverUrl($this->url()); ?>" method="post" name="digital-subscription-select">
    <fieldset class="account">
        <legend>Select Subscription</legend>
        <?php echo $this->digital_select_form->product_id->renderViewHelper(); ?>
        <?php echo $this->digital_select_form->product_id->renderErrors(); ?>
    </fieldset>
    <p class="submit"><input type="submit" value="Buy"></p>
</form>

