
<form action="<?php echo $this->serverUrl($this->url()); ?>" method="post" name="digital-subscription-select">
    <fieldset class="account">
        <legend>Select Subscription</legend>
        <?php echo $this->digital_select_form->product_id->renderViewHelper(); ?>
        <?php echo $this->digital_select_form->product_id->renderErrors(); ?>
    </fieldset>
    <p class="submit">
        <?php echo $this->digital_select_form->is_gift->renderViewHelper(); ?>
        <?php echo $this->digital_select_form->is_renewal->renderViewHelper(); ?>
        <input type="submit" value="Buy" class="button-grad">
    </p>
</form>

