
<div id="gifts">
    <div class="gifts-left">
        <img src="/images/product-types/large/gifts.jpg" width="450" height="630"> 
    </div>
    <div class="gifts-right">
        <div class="product-select-right-inner">
            <h2>Gift Subscriptions</h2>  
            <p>We now offer an easy way to give the gift of Elements knowledge to a friend or loved one who wants to learn more about Photoshop Elements.<p>
            <ul>
                <li>Choose an All-Access subscription to give either one or two years (6 issues or 12) of printed magazines plus full access to our subscriber website!</li>
                <li>From $59 per year, depending on the delivery address.</li>
            </ul>
            <ul class="buttons-list">
                <li>
                    <a href="<?php echo $this->serverUrl($this->url(array('zone_id' => 2, 'is_gift' => 1), 'products_subscription_options')); ?>" class="button-grad no-click">USA</a>
                </li>
                <li>
                    <a href="<?php echo $this->serverUrl($this->url(array('zone_id' => 1, 'is_gift' => 1), 'products_subscription_options')); ?>" class="button-grad no-click">Canada</a>
                </li>
                <li>
                    <a href="<?php echo $this->serverUrl($this->url(array('zone_id' => 3, 'is_gift' => 1), 'products_subscription_options')); ?>" class="button-grad no-click">International</a>
                </li>
            </ul>
        </div>
    </div>
</div>

