
<div id="products-main">
    <section class="subscriptions">
        <h3>Full Subscription</h3>
        <div class="description">
            <p>Description goes here</p>
        </div>
        <a href="<?php echo $this->serverUrl($this->url(array(), 'products_subscription')); ?>" class="select">Subscribe Now</a>
    </section>
    <section class="digital">
        <h3>Digital-Only Subscription</h3>
        <div class="description">
            <p>Description goes here</p>
        </div>
        <a href="<?php echo $this->serverUrl($this->url(array(), 'products_digital')); ?>" class="select">Subscribe Now</a>
    </section>
    <section class="dvds">
        <h3>DVDs</h3>
        <div class="description">
            <p>Description goes here</p>
        </div>
        <a href="<?php echo $this->serverUrl($this->url(array(), 'products_physical')); ?>" class="select">Shop for DVDs</a>
    </section>
    <section class="gifts">
        <h3>Gifts</h3>
        <div class="description">
            <p>Description goes here</p>
        </div>
        <a href="<?php echo $this->serverUrl($this->url(array(), 'products_gift_subscription')); ?>" class="select">Send a Gift</a>
    </section>
</div>
