
<?php echo $this->render('products/training.phtml'); ?>

<ul class="subscribe-renew">
    <li><a href="<?php echo $this->serverUrl($this->url(array(), 'products_special')); ?>" class="subscribe"><span>Subscribe</span></a></li>
    <li><a href="<?php echo $this->serverUrl($this->url(array(), 'products_renewal_options')); ?>" class="renew"><span>Renew</span></a></li>
</ul>

<div class="dvds">
    <section class="training">
        <h3>Training DVDs</h3>
        <ul>
            <li>
                <img src="/images/products/medium/LRNELEMENTS.jpg" width="185" height="176" alt="Learn Elements Today! (V.11)">
                <div class="copy">
                    <h4>Learn Elements Today! (V.11)</h4>
                    <h5>Elements 11 Edition – $35</h5>
                    <p>The best way to get up to speed with the features and workflow in Elements 11, whether a beginner or advanced user! </p>
                </div>
                <a href="<?php echo $this->serverUrl($this->url(array('product_id' => 170), 'products_physical_detail')); ?>" class="learn-more button-grad-yellow no-click">Learn More</a>
            </li>
            <li>
                <img src="/images/products/medium/LRNELEMENTS.jpg" width="185" height="176" alt="Learn Elements Today (V.9-10)">
                <div class="copy">
                    <h4>Learn Elements Today (V.9-10)</h4>
                    <h5>For Elements 9 and 10 – $30</h5>
                    <p>A complete 5 hour training course to help you learn how to get the most of Elements 9 10!</p>
                </div>
                <a href="<?php echo $this->serverUrl($this->url(array('product_id' => 170), 'products_physical_detail')); ?>" class="learn-more button-grad-yellow no-click">Learn More</a>
            </li>
        </ul>
    </section>
    <section class="tutorial">
        <h3>Tutorial DVDs</h3>
        <ul>
            <li>
                <img src="/images/products/medium/BODVD6.jpg" width="185" height="176" alt="Best of Photoshop Elements Techniques, V6">
                <div class="copy">
                    <h4>Best of P.E.T., Volume 6 ($35)</h4>
                    <p>65 easy-to-follow tutorials will guide you through Elements’ best features!</p>
                </div>
                <a href="<?php echo $this->serverUrl($this->url(array('product_id' => 173), 'products_physical_detail')); ?>" class="learn-more button-grad-yellow no-click">Learn More</a>
            </li>
            <li>
                <img src="/images/products/medium/BODVD5.jpg" width="185" height="176" alt="Best of Photoshop Elements Techniques, V5">
                <div class="copy">
                    <h4>Best of P.E.T., Volume 5 ($25)</h4>
                    <p>5 hours of creative projects, tips, and time-saving Elements techniques!</p>
                </div>
                <a href="<?php echo $this->serverUrl($this->url(array('product_id' => 172), 'products_physical_detail')); ?>" class="learn-more button-grad-yellow no-click">Learn More</a>
            </li>
            <li>
                <img src="/images/products/medium/BODVD4.jpg" width="185" height="176" alt="Best of Photoshop Elements Techniques, V4">
                <div class="copy">
                    <h4>Best of P.E.T., Volume 4 ($19)</h4>
                    <p>Add to your Elements expertise with 50+ inspiring tutorial videos.</p>
                </div>
                <a href="<?php echo $this->serverUrl($this->url(array('product_id' => 169), 'products_physical_detail')); ?>" class="learn-more button-grad-yellow no-click">Learn More</a>
            </li>
        </ul>
    </section>
</div>

<section class="gift">
    <h3>Do you know someone who would enjoy Photoshop Elements Techniques?</h3>
    <p><a href="<?php echo $this->serverUrl($this->url(array(), 'products_gifts')); ?>" class="button-grad">Gift a Subscription</a></p>
</section>

<div class="guarantee">
    <p><strong>Money-back guarantee:</strong> If you’re not happy with any purchase from Photoshop Elements Techniques, we’ll refund your money. It’s that easy.</p>
</div>

