
<?php echo $this->render('products/training.phtml'); ?>

<div class="subscribe-renew">
    <a href="#" class="subscribe"><span>Subscribe</span></a>
    <a href="#" class="renew"><span>Renew</span></a>
</div>
<section class="dvds">
    <h3>Tutorial DVDs</h3>
    <ul>
        <li>
            <img src="/images/products-index/dvds/LRNELEMENTS.jpg" width="185" height="176" alt="Learn Photoshop Elements Today!">
            <div class="copy">
                <h4>Learn Elements Today!</h4>
                <p>The best way to get up to speed with all the features in Elements, from beginner to advanced user!</p>
            </div>
            <a href="#" class="learn-more button-grad-yellow">Learn More</a>
        </li>
        <li>
            <img src="/images/products-index/dvds/BODVD6.jpg" width="185" height="176" alt="Best of Photoshop Elements Techniques, V6">
            <div class="copy">
                <h4>Best of P.E.T., Volume 6</h4>
                <p>65 easy-to-follow tutorials will guide you through Elements’ best features!</p>
            </div>
            <a href="#" class="learn-more button-grad-yellow">Learn More</a>
        </li>
        <li>
            <img src="/images/products-index/dvds/BODVD5.jpg" width="185" height="176" alt="Best of Photoshop Elements Techniques, V5">
            <div class="copy">
                <h4>Best of P.E.T., Volume 5</h4>
                <p>5 hours of creative projects, tips, and time-saving Elements techniques!</p>
            </div>
            <a href="#" class="learn-more button-grad-yellow">Learn More</a>
        </li>
        <li>
            <img src="/images/products-index/dvds/BODVD4.jpg" width="185" height="176" alt="Best of Photoshop Elements Techniques, V4">
            <div class="copy">
                <h4>Best of P.E.T., Volume 4</h4>
                <p>Add to your Elements expertise with 50+ inspiring tutorial videos.</p>
            </div>
            <a href="#" class="learn-more button-grad-yellow">Learn More</a>
        </li>
    </ul>
</section>
<section class="gift">
    <h3>Do you know someone who would enjoy Photoshop Elements Techniques?</h3>
    <p><a href="#" class="button-grad">Gift a Subscription</a></p>
</section>
<div class="guarantee">
    <p><strong>Money-back guarantee:</strong> If you’re not happy with any purchase from Photoshop Elements Techniques, we’ll refund your money. It’s that easy.</p>
</div>
<!--

<div id="products-main">
    <section class="subscriptions">
        <h3>Deluxe Subscription</h3>
        <div class="description">
            <p>Printed magazines and full online access</p>
        </div>
        <a href="<?php echo $this->serverUrl($this->url(array(), 'products_subscription')); ?>" class="select">Learn More</a>
    </section>
    <section class="digital">
        <h3>Digital-Only Subscription</h3>
        <div class="description">
            <p>Complete online access at a great price</p>
        </div>
        <a href="<?php echo $this->serverUrl($this->url(array(), 'products_digital')); ?>" class="select">Learn More</a>
    </section>
    <section class="dvds">
        <h3>Tutorial DVDs</h3>
        <div class="description">
            <p>Learn to master Elements through creative tutorial videos<br>produced by our editors &mdash; we have several options,<br> each packed with with great tutorials!</p>
        </div>
        <a href="<?php echo $this->serverUrl($this->url(array(), 'products_physical')); ?>" class="select">Shop for DVDs</a>
    </section>
    <section class="gifts">
        <h3>Gift subscriptions</h3>
        <div class="description">
            <p>Give the gift of learning to a friend or loved one<br>to help them get the most out of Elements!</p>
        </div>
        <a href="<?php echo $this->serverUrl($this->url(array(), 'products_gifts')); ?>" class="select">Send a Gift</a>
    </section>
</div>

-->
