
<h2>Magazine</h2>
<ul>
    <li>
        <h3>USA</h3>
        <p>From $59</p>
        <a href="<?php echo $this->serverUrl($this->url(array(), 'products_magazine')); ?>">Add to Cart</a>
    </li>
    <li>
        <h3>Canada</h3>
        <p>From $59</p>
        <a href="<?php echo $this->serverUrl($this->url(array(), 'products_magazine')); ?>">Add to Cart</a>
    </li>
    <li>
        <h3>International</h3>
        <p>From $59</p>
        <a href="<?php echo $this->serverUrl($this->url(array(), 'products_magazine')); ?>">Add to Cart</a>
    </li>
</ul>

