
<div id="physical" class="product-select">
    <div class="product-select-left digital-large"></div>
    <div class="product-select-right">
        <div class="product-select-right-inner">
            <h2>DVDs</h2>  
            <p>Ham hock tongue turkey bacon tenderloin brisket, frankfurter biltong pork loin pig. Shoulder leberkas bresaola, pastrami flank biltong jerky venison prosciutto beef ribs speck salami. Fatback pork pork loin, strip steak tri-tip meatloaf shankle rump. Andouille meatball flank chuck, speck beef ham hock cow.</p>
            <ul class="subscription-options">
                <?php foreach ($this->products as $product): ?>
                    <li>
                        <div class="subscription-option-left">
                            <h4 style="text-transform: none;"><?php echo $this->escape($product->name); ?></h4>
                            <p><?php echo $this->dollarFormat($product->cost); ?></p>
                        </div>
                        <div class="subscription-option-right">
                            <a href="<?php echo $this->serverUrl($this->url(array('product_id' => $product->product_id), 'cart_add')); ?>" class="button-grad-blue">Buy</a>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>
