
<section class="renewal-options">
    <h2>Renewal Options</h2>
    <p>Renew now and get an extra 2 months and “The Best of P.E.T., Vol. 6” as a thank you gift!</p>
    <a href="<?php echo $this->serverUrl($this->url(array('product_id' => 191, 'renewal' => 1), 'cart_add')); ?>" class="button-grad" id="product-191">1 Year &ndash; $59</a>
    <a href="<?php echo $this->serverUrl($this->url(array('product_id' => 188, 'renewal' => 1), 'cart_add')); ?>" class="button-grad" id="product-188">2 Years &ndash; $98</a>
</section>
