
<div id="products-renewal-options">
    <h2>Renewal Options</h2>
    <p>Renew now and get an extra 2 months and “The Best of P.E.T., Vol. 6” as a thank you gift!</p>
    <ul class="subscriptions">
        <?php foreach ($this->subscriptions as $sub): ?>
            <li><a href="<?php echo $this->serverUrl($this->url(array('product_id' => $sub->product_id, 'is_renewal' => 1, 'promo_code' => 'LUIS-USA'), 'cart_add')); ?>" class="button-grad cart-add"><?php echo $this->escape($sub->name); ?></a></li>
        <?php endforeach; ?>
    </ul>
</div>
