
<?php echo $this->render('products/training.phtml'); ?>
<section class="free-gifts">
    <h3>For a limited time, get 4 <b>bonus</b> issues and the "Learn Photoshop Elements Today" DVD!</h3>
    <ul>
        <li>We'll immediately send out our last 4 issues &mdash; 144 pages of easy-to-follow tutorials and Elements tips! </li>
        <li>“<b>Learn Photoshop Elements Today</b>” (a $50 value), our complete video training course that walks you through every feature in Elements!</li>
        <li>With your subscription, you'll have full and immediate access to the website, and your magazines will start arriving soon!</li>

    </ul>
    <p>This package is a great to get the most out of Elements, whether you’re a newcomer or a seasoned user!</p>
</section>
<div class="offers">
    <a href="<?php echo $this->serverUrl($this->url(array('term' => 1, 'promo_code' => '0812H'), 'products_subscription_zone')); ?>" class="offer-1"><span>One Year Subscription</span></a>
    <a href="<?php echo $this->serverUrl($this->url(array('term' => 2, 'promo_code' => '0812H'), 'products_subscription_zone')); ?>" class="offer-2"><span>Two Year Subscription</span></a>
</div>
<div class="guarantee">
    <p><strong>Money-back guarantee:</strong> If you’re not happy with any purchase from Photoshop Elements Techniques, we’ll refund your money. It’s that easy.</p>
</div>
