
<?php echo $this->render('products/training.phtml'); ?>
<section class="free-gifts">
    <h3>For a limited time, we’ll include $120 in free gifts as thanks for your subscription!</h3>
    <ul>
        <li>The “Best of Photoshop Elements Techniques” Volume 6 (a $30 value), our brand new DVD filled with creative tutorials, tips, and tricks</li>
        <li>The popular and fun Volume 5 in the “Best of P.E.T.” DVD series – 65 more projects to add to your Elements expertise</li>
        <li><strong>“Learn Elements Today”</strong> (a $50 value), our complete video training course for every feature in Elements 9, 10, or 11</li>
    </ul>
    <p>This package is simply the best way to get the most out of Elements, whether you’re a newcomer or a seasoned user!</p>
</section>
<div class="offers">
    <a href="<?php echo $this->serverUrl($this->url(array('term' => 12, 'promo_code' => '1012H'), 'products_subscription_zone')); ?>" class="offer-1"><span>One Year Subscription</span></a>
    <a href="<?php echo $this->serverUrl($this->url(array('term' => 24, 'promo_code' => '1012H'), 'products_subscription_zone')); ?>" class="offer-2"><span>Two Year Subscription</span></a>
</div>
<div class="guarantee">
    <p><strong>Money-back guarantee:</strong> If you’re not happy with any purchase from Photoshop Elements Techniques, we’ll refund your money. It’s that easy.</p>
</div>
