
<div id="subscription-zones" class="product-select">
    <div class="product-select-left subscriptions-large"></div>
    <div class="product-select-right">
        <div class="product-select-right-inner">
            <h2>Full Subscription</h2>  
            <p>Biltong salami tri-tip, shankle cow pastrami sausage frankfurter capicola ball tip kielbasa bresaola turkey short loin fatback. Short loin bresaola fatback jerky beef, prosciutto strip steak. Short ribs pig rump, jerky sirloin tri-tip speck pork beef ribs cow. Bacon beef ribs turducken, chicken tail ground round pork belly pork loin short ribs t-bone brisket cow. Beef ribs hamburger shoulder, boudin cow sirloin meatloaf swine.</p>
            <?php if (!$this->is_authenticated): ?>
                <h3>Pricing for your subscription to the magazine:</h3>
                <ul class="subscription-options">
                    <li>
                        <h4>USA</h4>
                        <p>From $59</p>
                        <a href="<?php echo $this->serverUrl($this->url(array('zone_id' => 2), 'products_subscription_select_term')); ?>" class="button-grad-blue">Go</a>
                    </li>
                    <li>
                        <h4>Canada</h4>
                        <p>From $69</p>
                        <a href="<?php echo $this->serverUrl($this->url(array('zone_id' => 1), 'products_subscription_select_term')); ?>" class="button-grad-blue">Go</a>
                    </li>
                    <li>
                        <h4>International</h4>
                        <p>From $95</p>
                        <a href="<?php echo $this->serverUrl($this->url(array('zone_id' => 3), 'products_subscription_select_term')); ?>" class="button-grad-blue">Go</a>
                    </li>
                </ul>
            <?php endif; ?>
        </div>
        <p class="renew"><a href="<?php echo $this->serverUrl($this->url(array(), 'products_subscription_renew')); ?>" class="button-grad">Renewing?</a></p>
    </div>
</div>

