
<form action="<?php echo $this->serverUrl($this->url()); ?>" method="post" name="subscription-select-term">
    <fieldset class="account">
        <legend>Select Term</legend>
        <?php echo $this->select_term_form->product_id->renderViewHelper(); ?>
        <?php echo $this->select_term_form->product_id->renderErrors(); ?>
    </fieldset>
    <p class="submit">
        <?php echo $this->select_term_form->zone_id->renderViewHelper(); ?>
        <?php echo $this->select_term_form->is_gift->renderViewHelper(); ?>
        <?php echo $this->select_term_form->is_renewal->renderViewHelper(); ?>
        <input type="submit" value="Buy" class="button-grad">
    </p>
</form>

