
<div id="products-subscription-options">
    <form action="<?php echo $this->serverUrl($this->url()); ?>" method="post" name="subscription-options">
        <h2><?php echo ($this->is_renewal ? 'Renewal' : 'Subscription'); ?> Options</h2>
        <section class="all-access">
            <h3>All Access Subscription</h3>
            <?php if ($this->is_renewal): ?>
                <p>Renew now and get an extra 2 months and “The Best of P.E.T., Vol. 6” as a thank you gift!</p>
            <?php else: ?>
                <p>The bi-monthly printed magazine, delivered to your door AND full access to our subscriber website.</p>
            <?php endif; ?>
            <ul class="options">
            <?php foreach ($this->regular_subs as $regular_sub): ?>
                <?php /* If term is defined, only show relevant subscription */ if ($this->term && $this->term != $regular_sub->term_months) { continue; } ?>
                <li>
                    <?php
                        /* Because of the product_id options having to be split up into two sections, we're not using the form elements directly --
                           using formRadio() view helper here, as well as below */
                        echo $this->formRadio('product_id', null, null, array($regular_sub->product_id => $regular_sub->name)) . ' &mdash; ';
                        echo $this->dollarFormat($regular_sub->cost); 
                        if (isset($last_regular_sub_cost) && $last_regular_sub_cost < $regular_sub->cost) {
                            echo ' &mdash; <em>Save ' . $this->dollarFormat(($last_regular_sub_cost) * 2 - $regular_sub->cost) . '</em>';
                        }
                        $last_regular_sub_cost = $regular_sub->cost;
                    ?>
                </li>
            <?php endforeach; ?>
            </ul>
        </section>
        <section class="digital">
            <h3>Don't need a printed magazine?</h3>
            <p>Get all of the great Photoshop Elements tutorials and videos online, without having to wait for &mdash; or pay postage for &mdash; the mail!</p> 
            <ul class="options">
                <?php foreach ($this->digital_subs as $digital_sub): ?>
                    <li>
                        <?php
                            echo $this->formRadio('product_id', null, null, array($digital_sub->product_id => $digital_sub->name)) . ' &mdash; ';
                            echo $this->dollarFormat($digital_sub->cost); 
                            if (isset($last_digital_sub_cost) && $last_digital_sub_cost < $digital_sub->cost) {
                                echo ' &mdash; <em>Save ' . $this->dollarFormat(($last_digital_sub_cost) * 2 - $digital_sub->cost) . '</em>';
                            }
                            $last_digital_sub_cost = $digital_sub->cost;
                        ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </section>
        <?php echo $this->sub_options_form->product_id->renderErrors(); ?>
        <div class="submit">
            <input type="submit" value="Add to Cart" class="button-grad">
            <?php echo $this->sub_options_form->zone_id->renderViewHelper(); ?>
            <?php echo $this->sub_options_form->is_gift->renderViewHelper(); ?>
            <?php echo $this->sub_options_form->is_renewal->renderViewHelper(); ?>
            <?php echo $this->sub_options_form->promo_code->renderViewHelper(); ?>
        </div>
    </form>
</div>
