<section class="products-training">
    <h2>The only training resource dedicated to Photoshop Elements</h2>
    <p>
        <em>Photoshop Elements Techniques</em> is a bi-monthly magazine along with a dynamic website packed with tutorial articles 
        and videos, all focused on teaching you how to get the most out of your digital photos using Photoshop Elements.
    </p>
    <h3>Your subscription includes:</h3>
    <ul>
        <li>Our beautiful, ad-free magazine, delivered bi-monthly to your door.</li>
        <li>
            Exclusive website access to more than 1,000 online videos, tutorials, and downloads &ndash;
            with new videos, articles, and tutorials every week!
        </li>
        <li>Downloadable PDFs of more than 8 years of back issues!</li>
    </ul>
</section>
