<section class="products-training">
    <h2>The only training resource dedicated to Photoshop Elements</h2>
    <p>
        <em>Photoshop Elements Techniques</em> offers tutorial articles, videos and a lively website all focused on helping you get the most out of Elements – whether you’re just getting started or are ready for the next level.  
    </p>
    <h3>What you get:</h3>
    <ul>
        <li>Easy to follow, web based video tutorials and articles explaining how to use every feature in Photoshop Elements</li>
        <li>A beautiful, bi-monthly magazine filled with tips, creative projects, and step-by-step techniques to help you learn quickly</li>
        <li>A rich archive (8 years so far) of downloadable issues, articles, and videos to let you learn the way that fits you best</li>
    </ul>
</section>
