
<div id="change-password">
    <form action="<?php echo $this->serverUrl($this->url()); ?>" method="post" name="change-password">
        <fieldset>
            <legend>Change Password for User <?php echo $this->escape($this->user->username); ?></legend>
            <dl class="form">
                <dt><?php echo $this->pw_form->new_password->renderLabel(); ?></dt>
                <dd>
                    <?php echo $this->pw_form->new_password->renderViewHelper(); ?>
                    <?php echo $this->pw_form->new_password->renderErrors(); ?>
                </dd>
                <dt><?php echo $this->pw_form->confirm_new_password->renderLabel(); ?></dt>
                <dd>
                    <?php echo $this->pw_form->confirm_new_password->renderViewHelper(); ?>
                    <?php echo $this->pw_form->confirm_new_password->renderErrors(); ?>
                </dd>
            </dl>
        </fieldset>
        <p class="submit">
            <input type="submit" value="Update" name="update">
            <input type="submit" value="Cancel" name="cancel">
        </p>
    </form>
</div>
