
<div id="user-detail">
    <section class="admin-list-left">
        <?php
            $url = $this->serverUrl($this->url(array('action' => 'edit', 'id' => $this->user->id))); 
            echo $this->objectToAdminList(array(
            'id'          => array(
                'title' => 'User ID',
                'callback' => function($data) use ($url) {
                    return '<a href="' . $url . '" title="Click to edit this user">' . $data->id . '</a>';
                },
            ),
            'username',
            'email'       => array('format' => 'email'),
            'date_joined' => array('format' => 'datetime'),
            'last_login'  => array('format' => 'datetime'),
            'is_active'   => array('title' => 'Active')
        ), $this->user); ?>
    </section>

    <section class="expirations admin-list-right">
        <?php echo $this->objectToAdminList(array(
            'regular'  => array('title' => 'Regular Expiration'),
            'digital'  => array('title' => 'Digital Expiration'),
            'previous' => array('title' => 'Previous Expiration')
        ), $this->expirations); ?>
    </section>

    <section class="billing admin-list-left">
        <h3>Billing</h3>
        <?php
        $user = $this->user;
        echo $this->objectToAdminList(array(
            'first_name'  => array(
                'title' => 'First Name',
                'callback' => function($data) use ($user) {
                    return $user->first_name;
                }
            ),
            'last_name'  => array(
                'title' => 'Last Name',
                'callback' => function($data) use ($user) {
                    return $user->last_name;
                }
            ),
            'billing_address'     => array('title' => 'Address'),
            'billing_address_2'   => array('title' => 'Address 2'),
            'billing_company'     => array('title' => 'Company'),
            'billing_city'        => array('title' => 'City'),
            'billing_state'       => array('title' => 'State'),
            'billing_country'     => array('title' => 'Country'),
            'billing_postal_code' => array('title' => 'Postal Code'),
            'billing_phone'       => array('title' => 'Phone')
        ), $this->profile); ?>
    </section>

    <section class="shipping admin-list-right">
        <h3>Shipping</h3>
        <?php echo $this->objectToAdminList(array(
            'shipping_first_name'  => array('title' => 'First Name'),
            'shipping_last_name'   => array('title' => 'Last Name'),
            'shipping_address'     => array('title' => 'Address'),
            'shipping_address_2'   => array('title' => 'Address 2'),
            'shipping_company'     => array('title' => 'Company'),
            'shipping_city'        => array('title' => 'City'),
            'shipping_state'       => array('title' => 'State'),
            'shipping_country'     => array('title' => 'Country'),
            'shipping_postal_code' => array('title' => 'Postal Code'),
            'shipping_phone'       => array('title' => 'Phone')
        ), $this->profile); ?>
    </section>

    <section class="orders clear full-width">
        <h3>Orders</h3>
        <?php 
            echo $this->objectsToAdminTable(array(
                'id'                 => array('title'  => 'Order ID'),
                'date_created'       => array(
                    'title'    => 'Order Date',
                    'format'   => 'datetime'
                ),
                'email',
                'billing_first_name' => array('title'  => 'First Name'),
                'billing_last_name'  => array('title'  => 'Last Name'),
                'total'              => array(
                    'title'   => 'Total',
                    'format'  => 'dollar'
                ),
                'view'               => array(
                    'format'  => 'link',
                    'label'   => 'View',
                    'url'     => '/admin/orders/detail/id'
                )
            ), $this->orders);
        ?>
    </section>

    <section class="shipping admin-list-left">
        <h3>Marketing</h3>
        <?php echo $this->objectToAdminList(array(
            'opt_in', 
            'opt_in_partner',
            'opt_in_subscriber',
            'comp',
            'version',
            'platform'
        ), $this->profile); ?>
    </section>

    <section class="user-notes clear full-width">
        <h3>Notes</h3>
        <?php if ($this->user_notes): ?>
        <?php
        $view = $this;
        echo $this->objectsToAdminTable(array(
            'date_created' => array('format' => 'datetime'),
            'note',
            'rep_user_name' => array('title' => 'Added By'),
            'delete' => array(
                //'url' => '/admin/users/delete-note-dialog/id'
                'title' => '',
                'callback' => function($data) use ($view) {
                    return '<a href="' . $view->serverUrl($view->url(array('action' => 'delete-note-dialog', 'id' => $data->id))) . '" class="delete">Delete</a>';
                }
            )
        ), $this->user_notes); ?>
        <?php else: ?>
        <p>No notes for this user</p>
        <?php endif; ?>
        <p><a href="<?php echo $this->serverUrl($this->url(array('action' => 'add-note', 'id' => null, 'user_id' => $this->user->id))); ?>" class="add-user-note">Add note</a></p>
    </section>
</div>

