
<div id="user-detail">
    <div class="addresses">
        <section class="admin-list-left">
            <h3>Billing</h3>
            <?php
                echo $this->escape($this->user->first_name) . ' ' . $this->escape($this->user->last_name) . '<br>';
                if ($this->profile->billing_company) {
                    echo $this->escape($this->profile->billing_company) . '<br>';
                }
                echo $this->escape($this->profile->billing_address) . '<br>';
                if ($this->profile->billing_address_2) {
                    echo $this->escape($this->profile->billing_address_2) . '<br>';
                }
                echo $this->escape($this->profile->billing_city) . ', ', $this->escape($this->profile->billing_state) . ' ' .
                    $this->escape($this->profile->billing_postal_code) . '<br>' .
                    $this->escape($this->profile->billing_country);
            ?>
        </section>

        <section class="admin-list-right">
            <h3>Shipping</h3>
            <?php
                echo $this->escape($this->profile->shipping_first_name) . ' ' . $this->escape($this->profile->shipping_last_name) . '<br>';
                if ($this->profile->shipping_company) {
                    echo $this->escape($this->profile->shipping_company) . '<br>';
                }
                echo $this->escape($this->profile->shipping_address) . '<br>';
                if ($this->profile->shipping_address_2) {
                    echo $this->escape($this->profile->shipping_address_2) . '<br>';
                }
                echo $this->escape($this->profile->shipping_city) . ', ', $this->escape($this->profile->shipping_state) . ' ' .
                    $this->escape($this->profile->shipping_postal_code) . '<br>' .
                    $this->escape($this->profile->shipping_country);
            ?>
        </section>
    </div>

    <section class="admin-list-left">
        <?php
            $url = $this->serverUrl($this->url(array('action' => 'edit', 'id' => $this->user->id))); 
            echo $this->objectToAdminList(array(
            'id'          => array(
                'title' => 'User ID',
                'callback' => function($data) use ($url) {
                    return '<a href="' . $url . '" title="Click to edit this user">' . $data->id . '</a>';
                },
            ),
            'username',
            'email'       => array('format' => 'email'),
            'date_joined' => array('format' => 'datetime'),
            'last_login'  => array('format' => 'datetime'),
            'is_active'   => array('title' => 'Active')
        ), $this->user); ?>
    </section>

    <section class="expirations admin-list-right">
        <?php echo $this->objectToAdminList(array(
            'expiration'          => array('title' => 'Expiration'),
            'previous_expiration' => array('title' => 'Previous Expiration')
        ), $this->user); ?>
    </section>

    <section class="orders clear full-width">
        <h3>Orders</h3>
        <?php 
            echo $this->objectsToAdminTable(array(
                'id'                 => array('title'  => 'Order ID'),
                'date_created'       => array(
                    'title'    => 'Order Date',
                    'format'   => 'datetime'
                ),
                'email',
                'billing_first_name' => array('title'  => 'First Name'),
                'billing_last_name'  => array('title'  => 'Last Name'),
                'total'              => array(
                    'title'   => 'Total',
                    'format'  => 'dollar'
                ),
                'view'               => array(
                    'format'  => 'link',
                    'label'   => 'View',
                    'url'     => '/admin/orders/detail/id'
                )
            ), $this->orders);
        ?>
        <p><a href="<?php echo $this->serverUrl($this->url(array('action' => 'add', 'controller' => 'orders', 'user_id' => $this->user->id, 'id' => null))); ?>" class="add-order">Add order</a></p>
    </section>

    <section class="shipping admin-list-left">
        <h3>Marketing</h3>
        <?php echo $this->objectToAdminList(array(
            'opt_in', 
            'opt_in_partner',
            'opt_in_subscriber',
            'comp',
            'version',
            'platform'
        ), $this->profile); ?>
    </section>

    <section class="user-notes clear full-width">
        <h3>Notes</h3>
        <?php if ($this->user_notes): ?>
        <?php
        $view = $this;
        echo $this->objectsToAdminTable(array(
            'date_created' => array('format' => 'datetime'),
            'note',
            'rep_user_name' => array('title' => 'Added By'),
            'delete' => array(
                //'url' => '/admin/users/delete-note-dialog/id'
                'title' => '',
                'callback' => function($data) use ($view) {
                    return '<a href="' . $view->serverUrl($view->url(array('action' => 'delete-note-dialog', 'id' => $data->id))) . '" class="delete">Delete</a>';
                }
            )
        ), $this->user_notes); ?>
        <?php else: ?>
        <p>No notes for this user</p>
        <?php endif; ?>
        <p><a href="<?php echo $this->serverUrl($this->url(array('action' => 'add-note', 'id' => null, 'user_id' => $this->user->id))); ?>" class="add-user-note">Add note</a></p>
    </section>
</div>

