
<div id="user-edit">
    <?php echo $this->flashMessenger($this->messages); ?>
    <form action="<?php echo $this->profile_form->getAction(); ?>" method="<?php echo $this->profile_form->getMethod(); ?>" name="<?php echo $this->profile_form->getName(); ?>">
        <div class="admin-form-left">
            <fieldset class="account">
                <legend>Account Information</legend>
                <dl class="form">
                    <dt><?php echo $this->profile_form->user->username->renderLabel(); ?></dt>
                    <dd>
                        <?php echo $this->profile_form->user->username->renderViewHelper(); ?>
                        <?php echo $this->profile_form->user->username->renderErrors(); ?>
                    </dd>
                    <dt><?php echo $this->profile_form->user->email->renderLabel(); ?></dt>
                    <dd>
                        <?php echo $this->profile_form->user->email->renderViewHelper(); ?>
                        <?php echo $this->profile_form->user->email->renderErrors(); ?>
                    </dd>
                    <dt><?php echo $this->profile_form->expiration->renderLabel(); ?></dt>
                    <dd>
                        <?php echo $this->profile_form->expiration->renderViewHelper(); ?>
                        <?php echo $this->profile_form->expiration->renderErrors(); ?>
                    </dd>
                </dl>
                <!--<p class="change-password"><a href="<?php echo $this->serverUrl($this->url(array(), 'change_password')); ?>">Change password</a></p>-->
            </fieldset>
            <fieldset class="billing">
                <legend>Billing Information</legend>
                <dl class="form">
                    <dt><?php echo $this->profile_form->user->first_name->renderLabel(); ?></dt>
                    <dd>
                        <?php echo $this->profile_form->user->first_name->renderViewHelper(); ?>
                        <?php echo $this->profile_form->user->first_name->renderErrors(); ?>
                    </dd>
                    <dt><?php echo $this->profile_form->user->last_name->renderLabel(); ?></dt>
                    <dd>
                        <?php echo $this->profile_form->user->last_name->renderViewHelper(); ?>
                        <?php echo $this->profile_form->user->last_name->renderErrors(); ?>
                    </dd>
                    <?php foreach ($this->profile_form->billing as $el): ?>
                        <dt><?php echo $el->renderLabel(); ?></dt>
                        <dd>
                            <?php echo $el->renderViewHelper(); ?>
                            <?php echo $el->renderErrors(); ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            </fieldset>
        </div>
        <div class="admin-form-right">
            <fieldset class="shipping">
                <legend>Shipping Information</legend>
                <dl class="form">
                    <?php foreach ($this->profile_form->shipping as $el): ?>
                        <dt><?php echo $el->renderLabel(); ?></dt>
                        <dd>
                            <?php echo $el->renderViewHelper(); ?>
                            <?php echo $el->renderErrors(); ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            </fieldset>
            <fieldset class="profile">
                <legend>Profile Information</legend>
                <dl class="form">
                    <dt class="version">
                        <label for="version">Version:</label>
                    </dt>
                    <dd class="version">
                        <?php echo $this->profile_form->info->version->renderViewHelper(); ?>
                        <?php echo $this->profile_form->info->version->renderErrors(); ?>
                    </dd>
                    <dt class="checkbox">
                        <label for="opt-in">Opt-in:</label>
                    </dt>
                    <dd class="checkbox">
                        <?php echo $this->profile_form->info->opt_in->renderViewHelper(); ?>
                        <?php echo $this->profile_form->info->opt_in->renderErrors(); ?>
                    </dd>
                    <dt class="checkbox">
                        <label for="opt-in-partner">Opt-in partner</label>
                    </dt>
                    <dd class="checkbox">
                        <?php echo $this->profile_form->info->opt_in_partner->renderViewHelper(); ?>
                        <?php echo $this->profile_form->info->opt_in_partner->renderErrors(); ?>
                    </dd>
                </dl>
            </fieldset>
        </div>
            <p class="update"><input type="submit" value="Update" id="update-submit"></p>
    </form>
</div>
