
<div id="user-edit">
    <?php echo $this->flashMessenger($this->messages); ?>
    <form action="<?php echo $this->user_form->getAction(); ?>" method="<?php echo $this->user_form->getMethod(); ?>" name="<?php echo $this->user_form->getName(); ?>">
        <div class="admin-form-left">
            <fieldset class="account">
                <legend>Account Information</legend>
                <dl class="form">
                    <dt><?php echo $this->user_form->user->username->getLabel(); ?></dt>
                    <dd>
                        <?php echo $this->user_form->user->username->renderViewHelper(); ?>
                        <?php echo $this->user_form->user->username->renderErrors(); ?>
                    </dd>
                    <dt><?php echo $this->user_form->user->email->getLabel(); ?></dt>
                    <dd>
                        <?php echo $this->user_form->user->email->renderViewHelper(); ?>
                        <?php echo $this->user_form->user->email->renderErrors(); ?>
                    </dd>
                    <?php if ($this->show_pw_fields): ?>
                    <dt><?php echo $this->user_form->user->password->getLabel(); ?></dt>
                    <dd>
                        <?php echo $this->user_form->user->password->renderViewHelper(); ?>
                        <?php echo $this->user_form->user->password->renderErrors(); ?>
                    </dd>
                    <dt><?php echo $this->user_form->user->confirm_password->getLabel(); ?></dt>
                    <dd>
                        <?php echo $this->user_form->user->confirm_password->renderViewHelper(); ?>
                        <?php echo $this->user_form->user->confirm_password->renderErrors(); ?>
                    </dd>
                    <?php endif; ?>
                    <?php if ($this->show_expiration_fields): ?>
                    <dt><?php echo $this->user_form->expiration->getLabel(); ?></dt>
                    <dd>
                        <?php echo $this->user_form->expiration->renderViewHelper(); ?>
                        <?php echo $this->user_form->expiration->renderErrors(); ?>
                    </dd>
                    <dt><?php echo $this->user_form->digital_only->getLabel(); ?></dt>
                    <dd>
                        <?php echo $this->user_form->digital_only->renderViewHelper(); ?>
                        <?php echo $this->user_form->digital_only->renderErrors(); ?>
                    </dd>
                    <?php endif; ?>
                    <dt><?php echo $this->user_form->is_active->getLabel(); ?></dt>
                    <dd>
                        <?php echo $this->user_form->is_active->renderViewHelper(); ?>
                        <?php echo $this->user_form->is_active->renderErrors(); ?>
                    </dd>
                </dl>
                <?php if (!$this->show_pw_fields): ?>
                    <p class="change-password"><a href="<?php echo $this->serverUrl($this->url(array('action' => 'change-password'))); ?>">Change password</a></p>
                <?php endif; ?>
            </fieldset>
            <fieldset class="billing">
                <legend>Billing Information</legend>
                <dl class="form">
                    <dt><?php echo $this->user_form->user->first_name->getLabel(); ?></dt>
                    <dd>
                        <?php echo $this->user_form->user->first_name->renderViewHelper(); ?>
                        <?php echo $this->user_form->user->first_name->renderErrors(); ?>
                    </dd>
                    <dt><?php echo $this->user_form->user->last_name->getLabel(); ?></dt>
                    <dd>
                        <?php echo $this->user_form->user->last_name->renderViewHelper(); ?>
                        <?php echo $this->user_form->user->last_name->renderErrors(); ?>
                    </dd>
                    <?php foreach ($this->user_form->billing as $el): ?>
                        <dt><?php echo $el->getLabel(); ?></dt>
                        <dd>
                            <?php echo $el->renderViewHelper(); ?>
                            <?php echo $el->renderErrors(); ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            </fieldset>
        </div>
        <div class="admin-form-right">
            <fieldset class="shipping">
                <legend>Shipping Information</legend>
                <p><a href="#" id="billing-to-shipping">Copy billing to shipping</a></p>
                <dl class="form">
                    <?php foreach ($this->user_form->shipping as $el): ?>
                        <dt><?php echo $el->getLabel(); ?></dt>
                        <dd>
                            <?php echo $el->renderViewHelper(); ?>
                            <?php echo $el->renderErrors(); ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            </fieldset>
            <fieldset class="profile">
                <legend>Profile Information</legend>
                <dl class="form">
                    <dt class="version">
                        <label for="version">Version:</label>
                    </dt>
                    <dd class="version">
                        <?php echo $this->user_form->info->version->renderViewHelper(); ?>
                        <?php echo $this->user_form->info->version->renderErrors(); ?>
                    </dd>
                    <dt class="checkbox">
                        <label for="opt-in">Opt-in:</label>
                    </dt>
                    <dd class="checkbox">
                        <?php echo $this->user_form->info->opt_in->renderViewHelper(); ?>
                        <?php echo $this->user_form->info->opt_in->renderErrors(); ?>
                    </dd>
                    <dt class="checkbox">
                        <label for="opt-in-partner">Opt-in partner</label>
                    </dt>
                    <dd class="checkbox">
                        <?php echo $this->user_form->info->opt_in_partner->renderViewHelper(); ?>
                        <?php echo $this->user_form->info->opt_in_partner->renderErrors(); ?>
                    </dd>
                </dl>
            </fieldset>
        </div>
        <p class="update clear">
            <?php echo $this->user_form->submit->renderViewHelper(); ?>
            <input type="submit" value="Cancel" name="cancel">
        </p>
    </form>
</div>
