
<form action="<?php echo $this->serverUrl($this->url()); ?>" method="get" name="search" id="search-form">
    <dl class="form">
        <dt class="date-start"><?php echo $this->search_form->start_date->getLabel(); ?></dt>
        <dd class="date-start">
            <?php echo $this->search_form->start_date->renderViewHelper(); ?>
            <?php echo $this->search_form->start_date->renderErrors(); ?>
        </dd>
        <dt class="date-end"><?php echo $this->search_form->end_date->getLabel(); ?></dt>
        <dd class="date-end">
            <?php echo $this->search_form->end_date->renderViewHelper(); ?>
            <?php echo $this->search_form->end_date->renderErrors(); ?>
        </dd>
        <dt class="search"><?php echo $this->search_form->search->getLabel(); ?></dt>
        <dd class="search">
            <?php echo $this->search_form->search->renderViewHelper(); ?>
            <?php echo $this->search_form->search->renderErrors(); ?>
        </dd>
    </dl>
    <p class="submit">
        <input type="submit" value="Search">
        <?php echo $this->search_form->sort->renderViewHelper(); ?>
        <?php echo $this->search_form->sort_dir->renderViewHelper(); ?>
    </p>
</form>

<?php
if ($this->orders) {

    $pagination = $this->paginationControl($this->paginator, 'Sliding', 'pagination/default.phtml', array('params' => $this->params));
    echo $pagination;
    echo $this->objectsToAdminTable(array(
        'id'           => array('title'  => 'User ID'),
        'date_joined'  => array(
            'title'    => 'Date Joined',
            'format'   => 'datetime'
        ),
        'username', 
        'email',
        'first_name',
        'last_name',
        'view'        => array(
            'format'  => 'link',
            'label'   => 'View',
            'url'     => '/admin/users/detail/id'
        )
    ), $this->orders, $this->params, array('sortable' => true));
    echo $pagination;
} else {
    echo '<p class="error">There are no orders to show</p>';
}
?>
