
<div id="confirmation">
    <h2>Thank You!</h2>
    <div class="confirmation-left">
        <p>We just sent you an email containing the information below. If you have any questions or concerns about this transaction, please contact us here: <a href="mailto:info@photoshopelementsuser.com">info@photoshopelementsuser.com</a>. We offer a no-hassle refund if you are not happy with your purchase.</p>
        <div class="sep">
            <section class="billing">
                <h4>Your billing details:</h4>
                <?php echo $this->escape($this->cart->user->first_name); ?>
                <?php echo $this->escape($this->cart->user->last_name); ?><br>
                <?php echo $this->escape($this->cart->billing->billing_address); ?><br>
                <?php echo ($this->cart->billing->billing_address_2 ? $this->escape($this->cart->billing->billing_address_2) . '<br>' : ''); ?>
                <?php echo ($this->cart->billing->billing_company ? $this->escape($this->cart->billing->billing_company) . '<br>' : ''); ?>
                <?php echo $this->escape($this->cart->billing->billing_city . ', ' . $this->cart->billing->billing_state . ' ' . $this->cart->billing->billing_postal_code); ?><br>
                <?php echo $this->escape($this->cart->billing->billing_country); ?>
            </section>
            <?php if ($this->cart->isShippingAddressRequired()): ?>
                <section class="shipping">
                    <h4>Your shipping details:</h4>
                    <?php if ($this->cart->use_shipping): ?>
                        <?php echo $this->escape($this->cart->shipping->shipping_first_name); ?>
                        <?php echo $this->escape($this->cart->shipping->shipping_last_name); ?><br>
                        <?php echo $this->escape($this->cart->shipping->shipping_address); ?><br>
                        <?php echo ($this->cart->shipping->shipping_address_2 ? $this->escape($this->cart->shipping->shipping_address_2) . '<br>' : ''); ?>
                        <?php echo ($this->cart->shipping->shipping_company ? $this->escape($this->cart->shipping->shipping_company) . '<br>' : ''); ?>
                        <?php echo $this->escape($this->cart->shipping->shipping_city . ', ' . $this->cart->shipping->shipping_state . ' ' . $this->cart->shipping->shipping_postal_code); ?><br>
                        <?php echo $this->escape($this->cart->shipping->shipping_country); ?>
                    <?php else: ?>
                        <?php echo $this->escape($this->cart->user->first_name); ?>
                        <?php echo $this->escape($this->cart->user->last_name); ?><br>
                        <?php echo $this->escape($this->cart->billing->billing_address); ?><br>
                        <?php echo ($this->cart->billing->billing_address_2 ? $this->escape($this->cart->billing->billing_address_2) . '<br>' : ''); ?>
                        <?php echo ($this->cart->billing->billing_company ? $this->escape($this->cart->billing->billing_company) . '<br>' : ''); ?>
                        <?php echo $this->escape($this->cart->billing->billing_city . ', ' . $this->cart->billing->billing_state . ' ' . $this->cart->billing->billing_postal_code); ?><br>
                        <?php echo $this->escape($this->cart->billing->billing_country); ?>
                    <?php endif; ?>
                </section>
            <?php endif; ?>
            <?php if ($this->cart->user->username): ?>
                <div class="login">
                    <a href="<?php echo $this->serverUrl($this->url(array('action' => 'confirmation-login', 'token' => $this->login_token))); ?>" class="button-grad-yellow">Log In Now</a>
                </div>
            <?php endif; ?>
        </div>
        <div class="sep">
            <table class="products">
                <thead>
                    <tr>
                        <th>What you will get:</th>
                        <th>Details:</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->cart->products as $product): ?>
                        <tr>
                            <td><?php echo $this->escape($product->getFullName()); ?></td>
                            <td>
                                <?php if ($this->cart->promo && !isset($promo_shown)): ?>
                                    <p><?php echo Markdown($this->cart->promo->receipt_description); $promo_shown = true; ?></p>
                                <?php endif; ?>
                                <?php if ($product->product_type_id == Model_ProductType::SUBSCRIPTION && !$product->isGift()): ?>
                                    <p>Your first magazine will be sent within 30 days, depending on when you placed your order and where that date falls in relation to our publication schedule.<br>
                                    <p>Any promotional materials will be shipped within 7 days of your order via USPS First Class Mail. Please allow 3 weeks for delivery.</p>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

