
<div id="checkout">
    <?php if (count($this->cart->products)): ?>
        <h2>Checkout</h2>
        <?php echo $this->flashMessenger($this->messages); ?>
        <form action="<?php echo $this->serverUrl($this->url()); ?>" method="post" name="checkout">
            <div class="checkout-left">
                <fieldset class="account<?php echo (!$this->is_authenticated ? ' med' : ''); ?>">
                    <legend>P.E.T. website login info</legend>
                    <dl class="form">
                        <?php if (!$this->is_authenticated && ($this->cart->products->hasDigitalSubscription() || $this->cart->products->hasSubscription())): ?>
                            <dt>
                                <?php echo $this->checkout_form->user->username->renderLabel(); ?>
                                <em>(Letters and numbers only)</em>
                            </dt>
                            <dd>
                                <?php echo $this->checkout_form->user->username->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->user->username->renderErrors(); ?>
                            </dd>
                            <dt>
                                <?php echo $this->checkout_form->user->password->renderLabel(); ?>
                                <em>(6 characters long, including at least one number)</em>
                            </dt>
                            <dd>
                                <?php echo $this->checkout_form->user->password->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->user->password->renderErrors(); ?>
                            </dd>
                            <dt><?php echo $this->checkout_form->user->confirm_password->renderLabel(); ?></dt>
                            <dd>
                                <?php echo $this->checkout_form->user->confirm_password->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->user->confirm_password->renderErrors(); ?>
                            </dd>
                        <?php endif; ?>
                        <dt>
                            <?php echo $this->checkout_form->user->email->renderLabel(); ?>
                            <em>(We will email your receipt here)</em>
                        </dt>
                        <dd>
                            <?php echo $this->checkout_form->user->email->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->user->email->renderErrors(); ?>
                        </dd>
                    </dl>
                </fieldset>
                <fieldset class="billing tall">
                    <legend>Enter your Billing Address</legend>
                    <?php if ($this->cart->isShippingAddressRequired()): ?>
                        <p class="use-shipping">
                            <?php echo $this->checkout_form->use_shipping; ?>
                        </p>
                    <?php endif; ?>
                    <dl class="form">
                        <dt><?php echo $this->checkout_form->user->first_name->renderLabel(); ?></dt>
                        <dd>
                            <?php echo $this->checkout_form->user->first_name->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->user->first_name->renderErrors(); ?>
                        </dd>
                        <dt><?php echo $this->checkout_form->user->last_name->renderLabel(); ?></dt>
                        <dd>
                            <?php echo $this->checkout_form->user->last_name->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->user->last_name->renderErrors(); ?>
                        </dd>

                        <dt><?php echo $this->checkout_form->billing->billing_address->renderLabel(); ?></dt>
                        <dd>
                            <?php echo $this->checkout_form->billing->billing_address->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->billing->billing_address->renderErrors(); ?>
                        </dd>
                        <dt><?php echo $this->checkout_form->billing->billing_address_2->renderLabel(); ?></dt>
                        <dd>
                            <?php echo $this->checkout_form->billing->billing_address_2->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->billing->billing_address_2->renderErrors(); ?>
                        </dd>
                        <dt><?php echo $this->checkout_form->billing->billing_company->renderLabel(); ?></dt>
                        <dd>
                            <?php echo $this->checkout_form->billing->billing_company->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->billing->billing_company->renderErrors(); ?>
                        </dd>
                        <dt><?php echo $this->checkout_form->billing->billing_city->renderLabel(); ?></dt>
                        <dd>
                            <?php echo $this->checkout_form->billing->billing_city->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->billing->billing_city->renderErrors(); ?>
                        </dd>
                        <dt><?php echo $this->checkout_form->billing->billing_state->renderLabel(); ?></dt>
                        <dd>
                            <?php echo $this->checkout_form->billing->billing_state->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->billing->billing_state->renderErrors(); ?>
                        </dd>
                        <dt><?php echo $this->checkout_form->billing->billing_postal_code->renderLabel(); ?></dt>
                        <dd>
                            <?php echo $this->checkout_form->billing->billing_postal_code->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->billing->billing_postal_code->renderErrors(); ?>
                        </dd>
                        <dt><?php echo $this->checkout_form->billing->billing_country->renderLabel(); ?></dt>
                        <dd>
                            <?php echo $this->checkout_form->billing->billing_country->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->billing->billing_country->renderErrors(); ?>
                        </dd>
                        <dt><?php echo $this->checkout_form->billing->billing_phone->renderLabel(); ?></dt>
                        <dd>
                            <?php echo $this->checkout_form->billing->billing_phone->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->billing->billing_phone->renderErrors(); ?>
                        </dd>
                    </dl>
                </fieldset>
                <fieldset class="profile">
                    <legend>Profile Information</legend>
                    <dl class="form">
                        <dt class="version">
                            <label for="version">What version of Photoshop Elements are you using?</label>
                        </dt>
                        <dd class="version">
                            <?php echo $this->checkout_form->info->version->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->info->version->renderErrors(); ?>
                        </dd>
                        <dt class="opt-in checkbox"></dt>
                        <dd class="opt-in checkbox">
                            <?php echo $this->checkout_form->info->opt_in->renderViewHelper(); ?>
                            <label for="opt-in">Please send me occasional email newsletters and let me know when my subscription needs to be renewed.</label>
                            <?php echo $this->checkout_form->info->opt_in->renderErrors(); ?>
                        </dd>
                        <dt class="opt-in-partner checkbox"></dt>
                        <dd class="opt-in-partner checkbox">
                            <?php echo $this->checkout_form->info->opt_in_partner->renderViewHelper(); ?>
                            <label for="opt-in-partner">I'd like to receive information from Photoshop Elements Techniques sponsors</label>
                            <?php echo $this->checkout_form->info->opt_in_partner->renderErrors(); ?>
                            <p class="note">
                                <em><strong>Note:</strong> Your contact information WILL NOT be sold or shared with any third party
                                companies or entities.</em>
                            </p>
                        </dd>
                    </dl>
                </fieldset>
            </div>
            <div class="checkout-middle">
                <?php if (!$this->cart->isFreeOrder()): ?>
                <fieldset class="payment med">
                    <legend>
                        Enter your Payment Info
                        <img src="/images/checkout/cc-logos.png" width="264" height="35" class="cc" alt="Credit card logos">
                    </legend>
                    <dl class="form">
                        <dt class="payment-method"><?php echo $this->checkout_form->payment->payment_method->getLabel(); ?></dt>
                        <dd class="payment-method">
                            <?php echo $this->checkout_form->payment->payment_method; ?>
                        </dd>
                    </dl>
                    <dl class="form cc<?php echo ($this->cart->payment->payment_method != 'credit_card' ? ' hide' : ''); ?>">
                        <dt><?php echo $this->checkout_form->payment->cc_num->renderLabel(); ?></dt>
                        <dd class="cc-num">
                            <?php echo $this->checkout_form->payment->cc_num->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->payment->cc_num->renderErrors(); ?>
                        </dd>
                        <dt class="cc-exp"><label>Expiration</label></dt>
                        <dd class="cc-exp">
                            <?php echo $this->checkout_form->payment->cc_exp_month->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->payment->cc_exp_year->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->payment->cc_exp_month->renderErrors(); ?>
                            <?php echo $this->checkout_form->payment->cc_exp_year->renderErrors(); ?>
                        </dd>
                        <dt class="cc-cvv"><?php echo $this->checkout_form->payment->cc_cvv->renderLabel(); ?></dt>
                        <dd class="cc-cvv">
                            <?php echo $this->checkout_form->payment->cc_cvv->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->payment->cc_cvv->renderErrors(); ?>
                        </dd>
                    </dl>
                </fieldset>
                <?php endif; ?>
                <?php if ($this->cart->isShippingAddressRequired()): ?>
                    <fieldset class="shipping tall<?php echo ($this->cart->use_shipping ? '' : ' hide'); ?>">
                        <legend>Ship your magazines to . . .</legend>
                        <dl class="form">
                            <dt><?php echo $this->checkout_form->shipping->shipping_first_name->renderLabel(); ?></dt>
                            <dd>
                                <?php echo $this->checkout_form->shipping->shipping_first_name->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->shipping->shipping_first_name->renderErrors(); ?>
                            </dd>
                            <dt><?php echo $this->checkout_form->shipping->shipping_last_name->renderLabel(); ?></dt>
                            <dd>
                                <?php echo $this->checkout_form->shipping->shipping_last_name->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->shipping->shipping_last_name->renderErrors(); ?>
                            </dd>
                            <dt><?php echo $this->checkout_form->shipping->shipping_address->renderLabel(); ?></dt>
                            <dd>
                                <?php echo $this->checkout_form->shipping->shipping_address->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->shipping->shipping_address->renderErrors(); ?>
                            </dd>
                            <dt><?php echo $this->checkout_form->shipping->shipping_address_2->renderLabel(); ?></dt>
                            <dd>
                                <?php echo $this->checkout_form->shipping->shipping_address_2->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->shipping->shipping_address_2->renderErrors(); ?>
                            </dd>
                            <dt><?php echo $this->checkout_form->shipping->shipping_company->renderLabel(); ?></dt>
                            <dd>
                                <?php echo $this->checkout_form->shipping->shipping_company->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->shipping->shipping_company->renderErrors(); ?>
                            </dd>
                            <dt><?php echo $this->checkout_form->shipping->shipping_city->renderLabel(); ?></dt>
                            <dd>
                                <?php echo $this->checkout_form->shipping->shipping_city->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->shipping->shipping_city->renderErrors(); ?>
                            </dd>
                            <dt><?php echo $this->checkout_form->shipping->shipping_state->renderLabel(); ?></dt>
                            <dd>
                                <?php echo $this->checkout_form->shipping->shipping_state->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->shipping->shipping_state->renderErrors(); ?>
                            </dd>
                            <dt><?php echo $this->checkout_form->shipping->shipping_postal_code->renderLabel(); ?></dt>
                            <dd>
                                <?php echo $this->checkout_form->shipping->shipping_postal_code->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->shipping->shipping_postal_code->renderErrors(); ?>
                            </dd>
                            <dt><?php echo $this->checkout_form->shipping->shipping_country->renderLabel(); ?></dt>
                            <dd>
                                <?php echo $this->checkout_form->shipping->shipping_country->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->shipping->shipping_country->renderErrors(); ?>
                            </dd>
                            <dt><?php echo $this->checkout_form->shipping->shipping_phone->renderLabel(); ?></dt>
                            <dd>
                                <?php echo $this->checkout_form->shipping->shipping_phone->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->shipping->shipping_phone->renderErrors(); ?>
                            </dd>
                        </dl>
                    </fieldset>
                <?php endif; ?>
                <fieldset class="promo-code">
                    <legend>Do you have a promo code?</legend>
                    <dl class="form">
                        <dt>
                            <?php echo $this->checkout_form->promo->promo_code->renderLabel(); ?>
                            <em>(Promo details will appear after you click "Apply")</em>
                        </dt>
                        <dd>
                            <?php echo $this->checkout_form->promo->promo_code->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->promo->promo_code->renderErrors(); ?>
                            <a href="#" class="button-grad">Apply</a>
                        </dd>
                    </dl>
                </fieldset>
                <p class="update">
                    <strong class="total">Total: <span class="total-value"><?php echo $this->dollarFormat($this->cart_totals['total']); ?></span></strong>
                    <input type="submit" value="Buy Now" class="button-grad-blue">
                </p>
                <p>We will email a receipt when the transaction processes.
                <br><em>We will not share your contact info with <strong>anyone</strong></em>.</p>

                <div id="promo-info">
                    <?php if ($this->cart->promo && $this->cart->promo->public_description): ?>
                        <h3>Your Promo</h3> 
                        <div class="promo-description">
                            <?php echo Markdown($this->cart->promo->public_description); ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
            <div class="checkout-right">
                <h3>In your cart:</h3>
                <ul class="cart">
                    <?php foreach ($this->cart->products as $product): ?>
                        <li class="product">
                            <?php echo $this->productThumbnail($product); ?>
                            <p><?php echo $this->escape($product->getFullName()); ?></p>
                        </li>
                    <?php endforeach; ?>
                </ul>
                <a href="<?php echo $this->serverUrl($this->url(array(), 'checkout_cart_reset')); ?>" class="button-grad cart-reset">Clear Cart</a>
            </div>
        </form>
    <?php else: ?>
        <p>You have no items in your cart. <a href="<?php echo $this->serverUrl($this->url(array(), 'products')); ?>">Continue shopping?</a></p>
    <?php endif; ?>
</div>
