
<?php print_r($this->checkout_form->getErrorMessages()); ?>
<div id="checkout">
    <?php if ($this->cart->hasProducts()): ?>
        <h2>Checkout</h2>
        <form action="<?php echo $this->serverUrl($this->url()); ?>" method="post" name="checkout">
            <?php echo $this->flashMessenger('checkout', true); ?>
            <div class="checkout-left">
                <fieldset class="account">
                    <legend>Account Information</legend>
                    <dl class="form">
                        <?php if (!$this->is_authenticated): ?>
                            <dt><?php echo $this->checkout_form->user->username->getLabel(); ?></dt>
                            <dd>
                                <?php echo $this->checkout_form->user->username->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->user->username->renderErrors(); ?>
                            </dd>
                            <dt><?php echo $this->checkout_form->user->password->getLabel(); ?></dt>
                            <dd>
                                <?php echo $this->checkout_form->user->password->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->user->password->renderErrors(); ?>
                            </dd>
                            <dt><?php echo $this->checkout_form->user->confirm_password->getLabel(); ?></dt>
                            <dd>
                                <?php echo $this->checkout_form->user->confirm_password->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->user->confirm_password->renderErrors(); ?>
                            </dd>
                        <?php endif; ?>
                        <dt><?php echo $this->checkout_form->user->email->getLabel(); ?></dt>
                        <dd>
                            <?php echo $this->checkout_form->user->email->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->user->email->renderErrors(); ?>
                        </dd>
                    </dl>
                </fieldset>
                <fieldset class="billing">
                    <legend>Enter your Billing Address</legend>
                    <p class="billing-to-shipping">
                        <?php echo $this->checkout_form->use_shipping; ?>
                    </p>
                    <dl class="form">
                        <dt><?php echo $this->checkout_form->user->first_name->getLabel(); ?></dt>
                        <dd>
                            <?php echo $this->checkout_form->user->first_name->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->user->first_name->renderErrors(); ?>
                        </dd>
                        <dt><?php echo $this->checkout_form->user->last_name->getLabel(); ?></dt>
                        <dd>
                            <?php echo $this->checkout_form->user->last_name->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->user->last_name->renderErrors(); ?>
                        </dd>

                        <dt><?php echo $this->checkout_form->billing->billing_address->getLabel(); ?></dt>
                        <dd>
                            <?php echo $this->checkout_form->billing->billing_address->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->billing->billing_address->renderErrors(); ?>
                        </dd>
                        <dt><?php echo $this->checkout_form->billing->billing_address_2->getLabel(); ?></dt>
                        <dd>
                            <?php echo $this->checkout_form->billing->billing_address_2->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->billing->billing_address_2->renderErrors(); ?>
                        </dd>
                        <dt><?php echo $this->checkout_form->billing->billing_company->getLabel(); ?></dt>
                        <dd>
                            <?php echo $this->checkout_form->billing->billing_company->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->billing->billing_company->renderErrors(); ?>
                        </dd>
                        <dt><?php echo $this->checkout_form->billing->billing_city->getLabel(); ?></dt>
                        <dd>
                            <?php echo $this->checkout_form->billing->billing_city->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->billing->billing_city->renderErrors(); ?>
                        </dd>
                        <dt><?php echo $this->checkout_form->billing->billing_state->getLabel(); ?></dt>
                        <dd>
                            <?php echo $this->checkout_form->billing->billing_state->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->billing->billing_state->renderErrors(); ?>
                        </dd>
                        <dt><?php echo $this->checkout_form->billing->billing_postal_code->getLabel(); ?></dt>
                        <dd>
                            <?php echo $this->checkout_form->billing->billing_postal_code->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->billing->billing_postal_code->renderErrors(); ?>
                        </dd>
                        <dt><?php echo $this->checkout_form->billing->billing_country->getLabel(); ?></dt>
                        <dd>
                            <?php echo $this->checkout_form->billing->billing_country->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->billing->billing_country->renderErrors(); ?>
                        </dd>
                        <dt><?php echo $this->checkout_form->billing->billing_phone->getLabel(); ?></dt>
                        <dd>
                            <?php echo $this->checkout_form->billing->billing_phone->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->billing->billing_phone->renderErrors(); ?>
                        </dd>
                    </dl>
                </fieldset>
                <fieldset class="payment">
                    <legend>Payment Information</legend>
                    <dl class="form">
                        <dt class="payment-method"><?php echo $this->checkout_form->payment->payment_method->getLabel(); ?></dt>
                        <dd class="payment-method">
                            <?php echo $this->checkout_form->payment->payment_method; ?>
                        </dd>
                    </dl>
                    <dl class="form cc<?php echo ($this->cart->payment->payment_method != 'credit_card' ? ' hide' : ''); ?>">
                        <dt><?php echo $this->checkout_form->payment->cc_num->getLabel(); ?></dt>
                        <dd class="cc-num">
                            <?php echo $this->checkout_form->payment->cc_num->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->payment->cc_num->renderErrors(); ?>
                        </dd>
                        <dt class="cc-exp"><label>Expiration</label></dt>
                        <dd class="cc-exp">
                            <?php echo $this->checkout_form->payment->cc_exp_month->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->payment->cc_exp_year->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->payment->cc_exp_month->renderErrors(); ?>
                            <?php echo $this->checkout_form->payment->cc_exp_year->renderErrors(); ?>
                        </dd>
                        <dt class="cc-cvv"><?php echo $this->checkout_form->payment->cc_cvv->getLabel(); ?></dt>
                        <dd class="cc-cvv">
                            <?php echo $this->checkout_form->payment->cc_cvv->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->payment->cc_cvv->renderErrors(); ?>
                        </dd>
                    </dl>
                </fieldset>
            </div>
            <div class="checkout-middle">
                <fieldset class="promo-code">
                    <legend>Enter Promo Code Here</legend>
                    <dl class="form">
                        <dt><?php echo $this->checkout_form->promo->promo_code->getLabel(); ?></dt>
                        <dd>
                            <?php echo $this->checkout_form->promo->promo_code->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->promo->promo_code->renderErrors(); ?>
                        </dd>
                    </dl>
                </fieldset>
                <?php if ($this->cart->isShippingAddressRequired()): ?>
                    <fieldset class="shipping<?php echo ($this->cart->use_shipping ? '' : ' hide'); ?>">
                        <legend>Enter your Shipping Address</legend>
                        <dl class="form">
                            <dt><?php echo $this->checkout_form->shipping->shipping_first_name->getLabel(); ?></dt>
                            <dd>
                                <?php echo $this->checkout_form->shipping->shipping_first_name->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->shipping->shipping_first_name->renderErrors(); ?>
                            </dd>
                            <dt><?php echo $this->checkout_form->shipping->shipping_last_name->getLabel(); ?></dt>
                            <dd>
                                <?php echo $this->checkout_form->shipping->shipping_last_name->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->shipping->shipping_last_name->renderErrors(); ?>
                            </dd>
                            <dt><?php echo $this->checkout_form->shipping->shipping_address->getLabel(); ?></dt>
                            <dd>
                                <?php echo $this->checkout_form->shipping->shipping_address->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->shipping->shipping_address->renderErrors(); ?>
                            </dd>
                            <dt><?php echo $this->checkout_form->shipping->shipping_address_2->getLabel(); ?></dt>
                            <dd>
                                <?php echo $this->checkout_form->shipping->shipping_address_2->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->shipping->shipping_address_2->renderErrors(); ?>
                            </dd>
                            <dt><?php echo $this->checkout_form->shipping->shipping_company->getLabel(); ?></dt>
                            <dd>
                                <?php echo $this->checkout_form->shipping->shipping_company->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->shipping->shipping_company->renderErrors(); ?>
                            </dd>
                            <dt><?php echo $this->checkout_form->shipping->shipping_city->getLabel(); ?></dt>
                            <dd>
                                <?php echo $this->checkout_form->shipping->shipping_city->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->shipping->shipping_city->renderErrors(); ?>
                            </dd>
                            <dt><?php echo $this->checkout_form->shipping->shipping_state->getLabel(); ?></dt>
                            <dd>
                                <?php echo $this->checkout_form->shipping->shipping_state->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->shipping->shipping_state->renderErrors(); ?>
                            </dd>
                            <dt><?php echo $this->checkout_form->shipping->shipping_postal_code->getLabel(); ?></dt>
                            <dd>
                                <?php echo $this->checkout_form->shipping->shipping_postal_code->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->shipping->shipping_postal_code->renderErrors(); ?>
                            </dd>
                            <dt><?php echo $this->checkout_form->shipping->shipping_country->getLabel(); ?></dt>
                            <dd>
                                <?php echo $this->checkout_form->shipping->shipping_country->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->shipping->shipping_country->renderErrors(); ?>
                            </dd>
                            <dt><?php echo $this->checkout_form->shipping->shipping_phone->getLabel(); ?></dt>
                            <dd>
                                <?php echo $this->checkout_form->shipping->shipping_phone->renderViewHelper(); ?>
                                <?php echo $this->checkout_form->shipping->shipping_phone->renderErrors(); ?>
                            </dd>
                        </dl>
                    </fieldset>
                <?php endif; ?>
                <fieldset class="profile">
                    <legend>Profile Information</legend>
                    <dl class="form">
                        <dt class="version">
                            <label for="version">What version of Photoshop Elements are you using?</label>
                        </dt>
                        <dd class="version">
                            <?php echo $this->checkout_form->info->version->renderViewHelper(); ?>
                            <?php echo $this->checkout_form->info->version->renderErrors(); ?>
                        </dd>
                        <dt class="opt-in checkbox"></dt>
                        <dd class="opt-in checkbox">
                            <?php echo $this->checkout_form->info->opt_in->renderViewHelper(); ?>
                            <label for="opt-in">I'd like to receive occasional information from Photoshop Elements Techniques</label>
                            <?php echo $this->checkout_form->info->opt_in->renderErrors(); ?>
                        </dd>
                        <dt class="opt-in-partner checkbox"></dt>
                        <dd class="opt-in-partner checkbox">
                            <?php echo $this->checkout_form->info->opt_in_partner->renderViewHelper(); ?>
                            <label for="opt-in-partner">I'd like to receive information from Photoshop Elements Techniques sponsors</label>
                            <?php echo $this->checkout_form->info->opt_in_partner->renderErrors(); ?>
                            <p class="note">
                                <em><strong>Note:</strong> Your contact information WILL NOT be sold or shared with any third party
                                companies or entities.</em>
                            </p>
                        </dd>
                    </dl>
                </fieldset>
                <p class="update"><input type="submit" value="Update" id="update-submit" class="button-grad"></p>
            </div>
            <div class="checkout-right">
            </div>
        </form>
    <?php else: ?>
        <p>You have no items in your cart. <a href="<?php echo $this->serverUrl($this->url(array(), 'products')); ?>">Continue shopping?</a></p>
    <?php endif; ?>
</div>
