
<form action="<?php echo $this->serverUrl($this->url()); ?>" method="post" name="change-password">
    <fieldset>
        <legend>Change Password</legend>
        <dl class="form">
            <dt><?php echo $this->pw_form->password->getLabel(); ?></dt>
            <dd>
                <?php echo $this->pw_form->password->renderViewHelper(); ?>
                <?php echo $this->pw_form->password->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->pw_form->new_password->getLabel(); ?></dt>
            <dd>
                <?php echo $this->pw_form->new_password->renderViewHelper(); ?>
                <?php echo $this->pw_form->new_password->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->pw_form->confirm_new_password->getLabel(); ?></dt>
            <dd>
                <?php echo $this->pw_form->confirm_new_password->renderViewHelper(); ?>
                <?php echo $this->pw_form->confirm_new_password->renderErrors(); ?>
            </dd>
        </dl>
    </fieldset>
    <p class="submit"><input type="submit" value="Update" class="button-grad"></p>
</form>

