
<?php if ($this->profile_updated): ?><p class="flash-message">Profile updated</p><?php endif; ?>
<form action="<?php echo $this->serverUrl($this->url()); ?>" method="<?php echo $this->profile_form->getMethod(); ?>" name="<?php echo $this->profile_form->getName(); ?>">
    <fieldset class="account">
        <legend>Account Information</legend>
        <dl class="form">
            <dt><?php echo $this->profile_form->username->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->username->renderViewHelper(); ?>
                <?php echo $this->profile_form->username->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->email->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->email->renderViewHelper(); ?>
                <?php echo $this->profile_form->email->renderErrors(); ?>
            </dd>
            <dt>Expiration</dt>
            <dd><?php /*echo $this->escape($this->subscription->expiration);*/ ?></dd>
        </dl>
        <p class="change-password"><a href="<?php echo $this->serverUrl($this->url(array(), 'change_password')); ?>">Change password</a></p>
    </fieldset>
    <fieldset class="billing">
        <legend>Billing Information</legend>
        <dl class="form">
            <dt><?php echo $this->profile_form->first_name->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->first_name->renderViewHelper(); ?>
                <?php echo $this->profile_form->first_name->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->last_name->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->last_name->renderViewHelper(); ?>
                <?php echo $this->profile_form->last_name->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->billing_address->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->billing_address->renderViewHelper(); ?>
                <?php echo $this->profile_form->billing_address->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->billing_address_2->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->billing_address_2->renderViewHelper(); ?>
                <?php echo $this->profile_form->billing_address_2->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->billing_company->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->billing_company->renderViewHelper(); ?>
                <?php echo $this->profile_form->billing_company->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->billing_city->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->billing_city->renderViewHelper(); ?>
                <?php echo $this->profile_form->billing_city->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->billing_state->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->billing_state->renderViewHelper(); ?>
                <?php echo $this->profile_form->billing_state->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->billing_postal_code->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->billing_postal_code->renderViewHelper(); ?>
                <?php echo $this->profile_form->billing_postal_code->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->billing_country->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->billing_country->renderViewHelper(); ?>
                <?php echo $this->profile_form->billing_country->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->billing_phone->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->billing_phone->renderViewHelper(); ?>
                <?php echo $this->profile_form->billing_phone->renderErrors(); ?>
            </dd>
        </dl>
    </fieldset>
    <fieldset class="shipping">
        <legend>Shipping Information</legend>
        <dl class="form">
            <dt><?php echo $this->profile_form->shipping_first_name->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->shipping_first_name->renderViewHelper(); ?>
                <?php echo $this->profile_form->shipping_first_name->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->shipping_last_name->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->shipping_last_name->renderViewHelper(); ?>
                <?php echo $this->profile_form->shipping_last_name->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->shipping_address->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->shipping_address->renderViewHelper(); ?>
                <?php echo $this->profile_form->shipping_address->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->shipping_address_2->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->shipping_address_2->renderViewHelper(); ?>
                <?php echo $this->profile_form->shipping_address_2->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->shipping_company->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->shipping_company->renderViewHelper(); ?>
                <?php echo $this->profile_form->shipping_company->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->shipping_city->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->shipping_city->renderViewHelper(); ?>
                <?php echo $this->profile_form->shipping_city->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->shipping_state->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->shipping_state->renderViewHelper(); ?>
                <?php echo $this->profile_form->shipping_state->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->shipping_postal_code->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->shipping_postal_code->renderViewHelper(); ?>
                <?php echo $this->profile_form->shipping_postal_code->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->shipping_country->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->shipping_country->renderViewHelper(); ?>
                <?php echo $this->profile_form->shipping_country->renderErrors(); ?>
            </dd>
            <dt><?php echo $this->profile_form->shipping_phone->getLabel(); ?></dt>
            <dd>
                <?php echo $this->profile_form->shipping_phone->renderViewHelper(); ?>
                <?php echo $this->profile_form->shipping_phone->renderErrors(); ?>
            </dd>
        </dl>
    </fieldset>
    <fieldset class="profile">
        <legend>Profile Information</legend>
        <dl class="form">
            <dt class="version">
                <label for="version">What version of Photoshop Elements are you using?</label>
            </dt>
            <dd class="version">
                <?php echo $this->profile_form->version->renderViewHelper(); ?>
                <?php echo $this->profile_form->version->renderErrors(); ?>
            </dd>
            <dt class="checkbox"></dt>
            <dd class="checkbox">
                <?php echo $this->profile_form->opt_in->renderViewHelper(); ?>
                <label for="opt-in">I'd like to receive occasional information from Photoshop Elements Techniques</label>
                <?php echo $this->profile_form->opt_in->renderErrors(); ?>
            </dd>
            <dt class="checkbox"></dt>
            <dd class="checkbox">
                <?php echo $this->profile_form->opt_in_partner->renderViewHelper(); ?>
                <label for="opt-in-partner">I'd like to receive information from Photoshop Elements Techniques sponsors</label>
                <?php echo $this->profile_form->opt_in_partner->renderErrors(); ?>
                <p class="note">
                    <strong>Note:</strong> Your contact information WILL NOT be sold or shared with any third party
                    companies or entities.
                </p>
            </dd>
        </dl>
    </fieldset>
    <p class="update"><input type="submit" value="Update" id="update-submit"></p>
</form>

