
<?php echo $this->flashMessenger('login', true); ?>
<form action="<?php echo $this->serverUrl($this->url()); ?>" method="post" name="login">
    <dl class="form">
        <dt><?php echo $this->login_form->username->getLabel(); ?></dt>
        <dd>
            <?php echo $this->login_form->username->renderViewHelper(); ?>
            <?php echo $this->login_form->username->renderErrors(); ?>
        </dd>
        <dt><?php echo $this->login_form->password->getLabel(); ?></dt>
        <dd>
            <?php echo $this->login_form->password->renderViewHelper(); ?>
            <?php echo $this->login_form->password->renderErrors(); ?>
        </dd>
    </dl>
    <p class="submit"><input type="submit" value="Login" id="login-submit"></p>
</form>
<p class="forgot-password"><a href="<?php echo $this->serverUrl($this->url(array(), 'reset_password_request')); ?>">Forgot your password?</a></p>
