
<form action="<?php echo $this->login_form->getAction(); ?>" method="<?php echo $this->login_form->getMethod(); ?>" name="<?php echo $this->login_form->getName(); ?>">
    <dl class="form">
        <dt><?php echo $this->login_form->username->getLabel(); ?></dt>
        <dd>
            <?php echo $this->login_form->username->renderViewHelper(); ?>
            <?php echo $this->login_form->username->renderErrors(); ?>
        </dd>
        <dt><?php echo $this->login_form->password->getLabel(); ?></dt>
        <dd>
            <?php echo $this->login_form->password->renderViewHelper(); ?>
            <?php echo $this->login_form->password->renderErrors(); ?>
        </dd>
    </dl>
    <p><input type="submit" value="Login" id="login-submit"></p>
</form>
<?php if ($this->login_failed): ?><p class="error">Login failed</p><?php endif; ?>
<p><a href="<?php echo $this->serverUrl($this->url(array(), 'reset_password_request')); ?>">Forgot your password?</a></p>
