
<form action="<?php echo $this->serverUrl($this->url()); ?>" method="post" name="reset-password-request">
    <fieldset class="account">
        <legend>Login Recovery</legend>
        <p>Forgotten your password or username? Enter your e-mail address below, and we'll give you your username and a link to reset your password.</p>
        <?php if ($this->email_invalid): ?><p class="error">That e-mail address doesn't have an associated user account. Are you sure you've registered?</p><?php endif; ?>
        <dl class="form">
            <dt><?php echo $this->pw_form->email->getLabel(); ?></dt>
            <dd>
                <?php echo $this->pw_form->email->renderViewHelper(); ?>
                <?php echo $this->pw_form->email->renderErrors(); ?>
            </dd>
        </dl>
    </fieldset>
    <p class="submit"><input type="submit" value="Submit"></p>
</form>

