
<?php if (!$this->invalid): ?>
    <form action="<?php echo $this->serverUrl($this->url()); ?>" method="<?php echo $this->pw_form->getMethod(); ?>" name="<?php echo $this->pw_form->getName(); ?>">
        <fieldset class="account">
            <legend>Reset Password</legend>
            <dl class="form">
                <dt><?php echo $this->pw_form->password->renderLabel(); ?></dt>
                <dd>
                    <?php echo $this->pw_form->password->renderViewHelper(); ?>
                    <?php echo $this->pw_form->password->renderErrors(); ?>
                </dd>
                <dt><?php echo $this->pw_form->confirm_password->renderLabel(); ?></dt>
                <dd>
                    <?php echo $this->pw_form->confirm_password->renderViewHelper(); ?>
                    <?php echo $this->pw_form->confirm_password->renderErrors(); ?>
                </dd>
            </dl>
        </fieldset>
        <p class="update"><input type="submit" value="Change Password" class="button-grad"></p>
    </form>
<?php else: ?>
    <p class="error">The link you followed is either expired or does not exist.</p>
    <p>Please try <a href="<?php echo $this->serverUrl($this->url(array(), 'reset_password_request')); ?>">resetting your password</a> once again.</p>
<?php endif; ?>

