
<div id="order-detail">
    
    <?php echo $this->flashMessenger($this->messages); ?>
    <h2>Order #<?php echo $this->escape($this->order->id); ?></h2>

    <section class="admin-list-left">
        <?php $url = $this->serverUrl($this->url(array('controller' => 'users', 'action' => 'detail', 'id' => $this->order->user_id)));?>
        <?php echo $this->objectToAdminList(array(
            'user_id'      => array(
                'callback' => function($data) use ($url) {
                    return '<a href="' . $url . '" title="View this user">' . $data->user_id . '</a>';
                },
                'title' => 'User ID'
            ),
            'username'     => array('callback' => function($data) {
                return $data->user->username;
            }),
            'date_created' => array('format' => 'datetime'),
            'date_updated' => array('format' => 'datetime'),
            'email' => array(
                'callback' => function($data) {
                    return '<a href="mailto:' . $data->email . '">' . $data->email . '</a>';
                }
            )
        ), $this->order); ?>
    </section>
    <section class="admin-list-right">
        <?php echo $this->objectToAdminList(array(
            'shipping'    => array('format' => 'dollar'),
            'discount'    => array('format' => 'dollar'),
            'total'       => array('format' => 'dollar'),
            'phone_order' => array('callback' => function($data) {
                return ($data->phone_order == 1 ? 'Y' : 'N');
            })

        ), $this->order); ?>
    </section>

    <section class="billing admin-list-left">
        <h3>Billing</h3>
        <?php echo $this->objectToAdminList(array(
            'billing_first_name'  => array('title' => 'First Name'),
            'billing_last_name'   => array('title' => 'Last Name'),
            'billing_address'     => array('title' => 'Address'),
            'billing_address_2'   => array('title' => 'Address 2'),
            'billing_company'     => array('title' => 'Company'),
            'billing_city'        => array('title' => 'City'),
            'billing_state'       => array('title' => 'State'),
            'billing_country'     => array('title' => 'Country'),
            'billing_postal_code' => array('title' => 'Postal Code'),
            'billing_phone'       => array('title' => 'Phone')
        ), $this->order); ?>
    </section>

    <section class="shipping admin-list-right">
        <h3>Shipping</h3>
        <?php echo $this->objectToAdminList(array(
            'shipping_first_name'  => array('title' => 'First Name'),
            'shipping_last_name'   => array('title' => 'Last Name'),
            'shipping_address'     => array('title' => 'Address'),
            'shipping_address_2'   => array('title' => 'Address 2'),
            'shipping_company'     => array('title' => 'Company'),
            'shipping_city'        => array('title' => 'City'),
            'shipping_state'       => array('title' => 'State'),
            'shipping_country'     => array('title' => 'Country'),
            'shipping_postal_code' => array('title' => 'Postal Code'),
            'shipping_phone'       => array('title' => 'Phone')
        ), $this->order); ?>
    </section>

    <section class="products clear full-width">
        <h3>Products</h3>
        <table class="admin-table">
            <tr>
                <th>Name</th>
                <th>SKU</th>
                <th>Quantity</th>
                <th>Gift?</th>
                <th>Unit Cost</th>
                <th>Total</th>
            </tr>
            <?php foreach ($this->order->products as $product): ?>
                <tr>
                    <td><?php echo $this->escape($product->name); ?></td>
                    <td><?php echo $this->escape($product->sku); ?></td>
                    <td><?php echo $this->escape($product->qty); ?></td>
                    <td><?php echo ($product->is_gift ? 'Y' : 'N'); ?></td>
                    <td><?php echo $this->dollarFormat($product->cost); ?></td>
                    <td><?php echo $this->dollarFormat($product->cost * $product->qty); ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </section>

    <section class="promo admin-list-left">
        <h3>Promotion</h3>
        <?php if ($this->order->promo): ?>
        <?php echo $this->objectToAdminList(array(
            'code',
            'expiration'  => array('format' => 'date')
            //'description'
        ), $this->order->promo); ?>
        <?php else: ?>
            <p class="no-data">No promotion</p>
        <?php endif; ?>
    </section>

    <section class="expirations admin-list-right">
        <h3>Subscription Expirations</h3>
        <?php echo $this->objectToAdminList(array(
            'regular' => array('title' => 'Regular Expiration'),
            'digital' => array('title' => 'Digital Expiration')
        ), $this->order->expirations); ?>
    </section>

    <section class="payments clear full-width">
        <h3>Payments</h3>
        <?php
        $view = $this;
        $payment_type_check = Model_PaymentType::CHECK;
        echo $this->objectsToAdminTable(array(
            'id'           => array(
                'title'  => 'Payment ID',
                'callback' => function($data) {
                    return $data->order_payment_id;
                }
            ),
            'date'  => array(
                'title'    => 'Date',
                'format'   => 'datetime'
            ),
            'payment_type_id' => array(
                'title' => 'Payment Type',
                'callback' => function($data) {
                    $value = $data->payment_type_id;
                    switch ($data->payment_type_id) {
                        case Model_PaymentType::PAYFLOW:
                            return 'Payflow';
                        case Model_PaymentType::PAYPAL:
                            return 'PayPal';    
                        case Model_PaymentType::CHECK:
                            return 'Check';
                        default:
                            return 'Unknown';    
                    }
                }
            ),
            'amount' => array('format' => 'dollar'), 
            'pnref'       => array('title' => 'PNREF'),
            'credit'      => array(
                'title'    => '',
                'callback' => function($data) use ($view, $payment_type_check) {
                    if ($data->amount > 0 && $data->payment_type_id != Model_PaymentType::CHECK) {
                        $url = $view->serverUrl($view->url(array(
                            'action'     => 'credit',
                            'controller' => 'payments',
                            'id'         => $data->order_payment_id
                        )));
                        return '<a href="' . $url . '" class="credit">Credit</a>';
                    }
                }
            ),
            'view' => array(
                'title' => '',
                'callback' => function($data) use ($view) {
                    $url = $view->serverUrl($view->url(array('controller' => 'payments', 'action' => 'detail', 'id' => $data->id)));
                    return "<a href=\"$url\">View</a>";
                }
            )
        ), $this->order->payments); ?>
    </section>
</div>
