
<h2>Order #<?php echo $this->escape($this->order->id); ?></h2>
<section class="basic">
    <?php echo $this->objectToAdminList(array(
        'user_id' => array(),
        'date_created' => array('format' => 'date'),
        'date_updated' => array('format' => 'date'),
        'email' => array()

    ), $this->order); ?>
</section>

<section class="billing">
    <?php echo $this->objectToAdminList(array(
        'billing_first_name',
        'billing_last_name',
        'billing_address',
        'billing_address_2',
        'billing_company',
        'billing_city',
        'billing_state',
        'billing_country',
        'billing_postal_code',
        'billing_phone'
    ), $this->order); ?>
</section>

<section class="shipping">
    <?php echo $this->objectToAdminList(array(
        'shipping_first_name',
        'shipping_last_name',
        'shipping_address',
        'shipping_address_2',
        'shipping_company',
        'shipping_city',
        'shipping_state',
        'shipping_country',
        'shipping_postal_code',
        'shipping_phone'
    ), $this->order); ?>
</section>

<!--
<section>
    <dl>
        <dt>User ID:</dt>
        <dd><?php echo $this->escape($this->order->user->id); ?></dd>
        <?php if ($this->order->promo): ?>
            <dt>Promotion:</dt>
            <dd><?php echo $this->escape($this->order->promo->code); ?></dd>
        <?php endif; ?>
        <dt>Date Created:</dt>
        <dd><?php $date_created = new DateTime($this->order->date_created); echo $this->escape($date_created->format('M j, Y h:i:s a')); ?></dd>
        <dt>Date Updated:</dt>
        <dd><?php $date_updated = new DateTime($this->order->date_updated); echo $this->escape($date_updated->format('M j, Y h:i:s a')); ?></dd>
        <dt>Email:</dt>
        <dd><?php echo $this->escape($this->order->email); ?></dd>
        <dt>Billing First Name:</dt>
        <dd><?php echo $this->escape($this->order->billing_first_name); ?></dd>
        <dt>Billing Last Name:</dt>
        <dd><?php echo $this->escape($this->order->billing_last_name); ?></dd>
        <dt>:</dt>
        <dd><?php echo $this->escape($this->order->user->id); ?></dd>
        <dt>:</dt>
        <dd><?php echo $this->escape($this->order->user->id); ?></dd>
        <dt>:</dt>
        <dd><?php echo $this->escape($this->order->user->id); ?></dd>
        <dt>:</dt>
        <dd><?php echo $this->escape($this->order->user->id); ?></dd>
    </dl>
</section>
-->
<pre>
<?php print_r($this->order); ?>
</pre>
