
<form action="<?php echo $this->serverUrl($this->url()); ?>" method="get" name="search" id="search-form">
    <dl class="form">
        <dt class="date-start"><?php echo $this->search_form->start_date->getLabel(); ?></dt>
        <dd class="date-start">
            <?php echo $this->search_form->start_date->renderViewHelper(); ?>
            <?php echo $this->search_form->start_date->renderErrors(); ?>
        </dd>
        <dt class="date-end"><?php echo $this->search_form->end_date->getLabel(); ?></dt>
        <dd class="date-end">
            <?php echo $this->search_form->end_date->renderViewHelper(); ?>
            <?php echo $this->search_form->end_date->renderErrors(); ?>
        </dd>
        <dt class="search"><?php echo $this->search_form->search->getLabel(); ?></dt>
        <dd class="search">
            <?php echo $this->search_form->search->renderViewHelper(); ?>
            <?php echo $this->search_form->search->renderErrors(); ?>
        </dd>
        <dt class="sort_dir"><?php echo $this->search_form->sort_dir->getLabel(); ?></dt>
        <dd class="sort_dir">
            <?php echo $this->search_form->sort_dir->renderViewHelper(); ?>
            <?php echo $this->search_form->sort_dir->renderErrors(); ?>
        </dd>
    </dl>
    <p class="submit">
        <input type="submit" value="Search">
        <?php echo $this->search_form->sort->renderViewHelper(); ?>
    </p>
</form>

<?php
if ($this->orders) {

    $pagination = $this->paginationControl($this->paginator, 'Sliding', 'pagination/default.phtml', array('params' => $this->params));
    echo $pagination;
    echo $this->objectsToAdminTable(array(
        'id'                 => array('title'  => 'Order ID'),
        'date_created'       => array(
            'title'  => 'Date',
            'type'   => 'date'
        ),
        'email'              => array('title'  => 'Email'),
        'billing_first_name' => array('title'  => 'First Name'),
        'billing_last_name'  => array('title'  => 'Last Name'),
        'total'              => array(
            'title' => 'Total',
            'type'  => 'dollar'
        ),
        'view'               => array(
            'type'  => 'view',
            'label' => 'View',
            'url'   => '/admin/orders/detail/id'
        )
    ), $this->orders, $this->params);
    echo $pagination;
} else {
    echo '<p class="error">There are no orders to show</p>';
}
?>
